### ISSUE TITLE
typo at wmain

### ISSUE THREAD

**Issue by dscharalampidis** [MicrosoftDocs/cpp-docs#4337] opened 2022-12-13 00:37 UTC
I believe that the `w` before `main` at `wmain` is a typo.

The `argv` and `envp` parameters to `wmain` can also be defined as type `char**`. For more information about the arguments, see [Argument description](https://learn.microsoft.com/en-us/cpp/c-language/argument-description?view=msvc-170).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87d71a04-aab4-5d43-3797-c3e44ce58b61
* Version Independent ID: a4cab9fc-9f34-856a-2309-858d2e67640f
* Content: [main function and program execution](https://learn.microsoft.com/en-us/cpp/c-language/main-function-and-program-execution?view=msvc-170)
* Content Source: [docs/c-language/main-function-and-program-execution.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/main-function-and-program-execution.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-12-13 00:59
@dscharalampidis 

Thanks for writing in. It's not a typo. `wmain` is a Microsoft extension of `main` to wide characters, in this case, `wchar_t` types encoding UTF-16LE. It works as described, when /DUNICODE is defined:

```
// wmain_example.cpp
#include <iostream>
#include <string>

int wmain(int argc, wchar_t** argv, wchar_t** envp)
{
	std::wcout << L"Argument count: " << argc << L"\n";
	for (int i = 0; i < argc; ++i)
	{
		std::wstring arg{ argv[i] };
		std::wcout << L"argv[" << i << L"]: " << arg << L"\n";
	}
}
```

Since it works as described, I'm closing the issue as by design.

**Closed by corob-msft** 2022-12-13 00:59 UTC
Labels: Closed - by design
