### ISSUE TITLE
There is a long time bug under VC++ [bug]

### ISSUE THREAD

**Issue by nil-ref** [MicrosoftDocs/cpp-docs#3999] opened 2022-06-22 03:13 UTC
do{
        printf("test");
        continue;
        }
    while (0);

It only prints once!

This problem has existed for several years.

MSVC: 14.33.31424  in VS2022 17.3.0 preview 1.1

**Comment by corob-msft** [comment] 2022-06-22 03:37
@nil-ref 

If you think you've found a bug in the compiler, we can't do anything about it in the documentation. Bugs should be reported on the C++ [Developer Community](https://aka.ms/vsfeedback/browsecpp) page. For more information, see [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170). As a result, I'm closing the issue.

However, in this case, the behavior is not a bug. A `continue` statement in a loop jumps directly to the loop's conditional test, skipping any intervening code. The code is doing exactly what you told it to do: it jumps to the `while (0);` statement and exits the loop. Every C and C++ compiler behaves this way, and always has.

**Closed by corob-msft** 2022-06-22 03:37 UTC
Labels: product-feedback, not-a-doc-issue, Closed - by design
