### ISSUE TITLE
Behaviour of _getch different from documentation

### ISSUE THREAD

**Issue by ogdenpm** [MicrosoftDocs/cpp-docs#473] opened 2018-10-16 17:36 UTC
[Enter feedback here]
Either the implementation of _getch or the **remarks** are incorrect for VS2017 15.8.7.
Testing has revealed that two calls must always be made to **_getch**.
For function keys or arrow keys the behaviour is as noted, for other keys the first value is the actual key code, the second call returns 0.
Additionally CTRL+C is actually returned as 03 00 despite the comment that it cannot be read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c56cd0-6b04-3472-ce56-fe749a238b70
* Version Independent ID: 5e6e3834-0c3c-0677-9dc2-9e7a96d31f0c
* Content: [_getch, _getwch](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(CONIO%2F_getch);k(_getch);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/getch-getwch.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/getch-getwch.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-10-17 00:05
@ogdenpm I see you're correct, at least when running code built using the 19.15 version of cl and the latest UCRT bits from the Windows 10 SDK in the VS2017 developer command prompt on whatever recent version of 64-bit Windows 10 my machine has on it, talking to my 125-key ergo keyboard. I'm guessing that the documentation was true at one time, but there's no telling what changed, or when, to make it behave the way it does now. This will take some research.

**Comment by corob-msft** [comment] 2018-12-18 04:07
@tomruen This is an issue for a particular version of the UCRT bits that shipped in an update of Windows, and the corresponding build of the Windows SDK, which was also shipped with a few of the recent minor releases of Visual Studio. For all the gory details, check out [_getch() broken in VS 15.7](https://developercommunity.visualstudio.com/content/problem/247770/-getch-broken-in-vs-157.html) on Developer Community, and see the comments in the solutions from @stwish-msft.

To resolve this issue, the quick solution is to install an [update to Windows 10 version 1809](https://support.microsoft.com/en-us/help/4464330/windows-10-update-kb4464330) to pick up the fixed library, and also to run the Visual Studio Installer again to pick up the latest Windows SDK, available under the **Individual components** tab in the **SDKs, libraries, and frameworks** section, for example, **Windows 10 SDK (10.0.17763.0)** or later. Fixes for other scenarios such as downlevel OSes, merge modules, and app-local or static deployment are discussed in the Developer Community comments as well.

Since this isn't a documentation issue, I'm closing it. If you have an issue with the product or libraries, the best place to bring it up is the [Developer Community C++ forum](https://developercommunity.visualstudio.com/spaces/62/index.html). Odds are at least fair that someone else has run into the issue and reported it already, so it pays to search first. If you don't see your particular issue, we have some instructions on how to write a bug report that's easy for the developers to reproduce and fix in [How to report a problem with the Visual C++ toolset or documentation](https://docs.microsoft.com/en-us/cpp/how-to-report-a-problem-with-the-visual-cpp-toolset). Thanks for your patience.

**Closed by corob-msft** 2018-12-18 04:07 UTC
Labels: P2, doc-bug, on backlog

**Comment by corob-msft** [comment] 2018-12-18 04:14
I forgot to mention that you also need to update your projects to point to the new Windows SDK you install. To do that, go to the **Project Properties** dialog and set the **Configuration** to **All Configurations** and the **Platform** to **All Platforms**, then on the **Configuration Properties** > **General** page, set the **Windows SDK Version** to **10.0.17763.0** or later.
