### ISSUE TITLE
Example Output Problem

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#558] opened 2018-11-16 19:08 UTC
@YuiAki commented on [Fri Nov 16 2018](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/issues/42)

There is an error on Example  Output part.For "string = -10110134932This stopped it",the output should be "strtol = -10110134932" but "strtol = -2147483648".

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0656f7f5-94a4-e2cd-c0ff-7949a271dd45
* Version Independent ID: 7f8311a0-098a-d03e-d215-61c00c88966e
* Content: [strtod、_strtod_l、wcstod、_wcstod_l](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-11-16 20:02
@YuiAki 

This might be confusing because a **long** is a 32-bit type in the Microsoft compiler. When I build the crt_strtod.c sample for x86 and x64, the value returned by `strtol` matches the output shown. This is the expected behavior for [strtol](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/reference/strtol-wcstol-strtol-l-wcstol-l?view=vs-2017), which returns `LONG_MAX` (2147483647) or `LONG_MIN` (-2147483648) on overflow, depending on the sign of the converted value.  The `strtoll` function would return the value -10110134932, because that does not overflow a 64-bit **long long** type. I'm closing this issue, because it doesn't appear to be a documentation bug.

**Closed by corob-msft** 2018-11-16 20:02 UTC
Labels: not-a-doc-issue
