### ISSUE TITLE
VS2019 warn about switch->fall-through but doesn't recognize the attribute

### ISSUE THREAD

**Issue by A-x-S** [MicrosoftDocs/cpp-docs#3504] opened 2021-11-05 20:32 UTC
The article describes that VS2017 doesn't warn about fall-throughs in switch statements and therefor the attribute [[fallthrough]] has no effect.
Wath's not mentioned is that VS2019 does warn about those possible mistakes, but the attribute **still doesn't have any effect**, so it's **useless to annotate** intended fall-throughs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2eb231e-d120-ad82-539c-f30baa904815
* Version Independent ID: ea724ca8-bc1c-f154-c122-0217f6280590
* Content: [Attributes in C++](https://docs.microsoft.com/en-us/cpp/cpp/attributes?view=msvc-160)
* Content Source: [docs/cpp/attributes.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/attributes.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-11-05 22:26
@A-x-S 

I'm sorry it's giving you trouble. Unfortunately, I can't reproduce the effect you describe. The VS 2019 compiler doesn't have a warning about implicit fallthrough. There are only warnings about improper use of the `[[fallthrough]]` attribute: either C5051 (must use **`/std:c++17`** or later) or C4468 (attribute must be followed by a `case` or `default` label). These worked as described in the docs in my testing.

The code analysis engine does have such a warning: [C26819](https://docs.microsoft.com/en-us/cpp/code-quality/c26819). It detects and warns on unannotated fallthrough if **`/std:c++17`** or later is applied. As far as I can tell, it works as intended. If you have a case where it doesn't work, then you can report a problem on [Developer Community](https://aka.ms/vsfeedback/browsecpp), since that would be considered a product issue.

Test rig, adapted from [cppreference](https://en.cppreference.com/w/cpp/language/attributes/fallthrough):
```
C:\Users\corob\Documents\Projects\curiosity\fallthrough>type fallthrough.cpp
void f(int n) {
    void a(), b(), c();
    switch (n) {
    case 1:
    case 2:
        a();
        [[fallthrough]];
    case 3: // no warning on fallthrough
        b();
    case 4: // compiler may warn on fallthrough
        if(n < 3) {
            c();
            [[fallthrough]]; // not followed by label
        }
        else {
            return;
        }
    default:
        [[fallthrough]]; // ill-formed, no subsequent case or default label
  }
}

C:\Users\corob\Documents\Projects\curiosity\fallthrough>cl /EHsc /c /nologo /Wall /permissive- /analyze /analyze:plugin EspxEngine.dll /std:c++17 fallthrough.cpp
fallthrough.cpp
fallthrough.cpp(13): warning C4468: 'fallthrough': attribute must be followed by a case label or a default label
fallthrough.cpp(19): warning C4468: 'fallthrough': attribute must be followed by a case label or a default label
C:\Users\corob\Documents\Projects\curiosity\fallthrough\fallthrough.cpp(10) : warning C26819: Unannotated fallthrough between switch labels (es.78).
```

I'm closing this as not repro, but I'll reopen it if you have an example where the behavior doesn't match the documentation.

**Closed by corob-msft** 2021-11-05 22:26 UTC
Labels: product-feedback, Closed - not repro
