### ISSUE TITLE
It didn't work.

### ISSUE THREAD

**Issue by zevfarkas** [MicrosoftDocs/cpp-docs#2060] opened 2020-04-06 00:07 UTC
I had the same issue as natanfudge. I started the project over again, and it did compile, but when it runs, it just puts up an empty window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-04-22 10:02
@zevfarkas 
Sorry it's giving you trouble. I couldn't reproduce your error when I ran through the instructions in VS 2019. You could try a breakpoint on the `TextOut` call (around line 127 in the code) to make sure the code that writes inside the window actually gets called. It can take a long time for the window to appear the first time you run it. Visual Studio first tries to load lots of debugging symbols before it puts the app up. Something similarly lengthy runs the first time you dismiss the app. I'm closing this as a support issue, not a doc issue for now. If you find that some instructions here led you astray, add a comment, and I'll look into it again.

**Closed by corob-msft** 2020-04-22 10:02 UTC
Labels: doc-enhancement
