### ISSUE TITLE
nmake special characters?

### ISSUE THREAD

**Issue by jhamilton68** [MicrosoftDocs/cpp-docs#3668] opened 2022-01-26 15:30 UTC
In the special characters section of the "NMAKE makefile contents and features page," 13 special characters are listed but the section only describes how to escape the characters and treat them as literals, not what the special characters mean or where to find more information about them.  This has been my biggest frustration with Microsoft's on-line documentation, there seems to be an endless trail of links to articles with very little meaningful content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a120d1f2-bf1e-7138-c02a-fb94b88b9d36
* Version Independent ID: 8e0bb9f2-8d1a-f56b-3084-80a9c3cd8e9b
* Content: [NMAKE makefile contents and features](https://docs.microsoft.com/en-us/cpp/build/reference/contents-of-a-makefile?view=msvc-170)
* Content Source: [docs/build/reference/contents-of-a-makefile.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/contents-of-a-makefile.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-01-27 00:34
@jhamilton68 

Thanks for sharing your idea. That's an interesting notion that seems a little outside the scope of the section's intent. The intent behind this section is, "These are the characters you may need to escape to prevent unexpected behavior in a makefile."  I don't expect people start here to find an answer to a question like "What does `!` mean in a makefile," though it might occur to them when they read the list, like it did for you. We describe these characters' use in context in other articles, where you'd learn, for instance, that `!` is a modifier for a command to apply it to all dependent files, or it's a prefix to a makefile preprocessor directive, or it's the unary logical "not" operator in a makefile preprocessor expression. It doesn't really make sense to duplicate all of that information in a section that's intended to tell you which characters you may need to escape, and how to escape them. I'm closing your issue as an idea that we won't implement, because the document is doing what we intend.

**Closed by corob-msft** 2022-01-27 00:34 UTC
Labels: doc-idea, Closed - by design
