### ISSUE TITLE
Debug folder under \bin folder

### ISSUE THREAD

**Issue by mohowzeh** [MicrosoftDocs/cpp-docs#2536] opened 2020-10-15 13:39 UTC
The article suggests that the debug folder is under repos, but this is not the case for projects that have been started with the option "Save project and solution in same folder". 
In the latter case, the \debug folder will be a subfolder of the \bin folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d597b582-59ec-2014-699b-6aac8db69cf6
* Version Independent ID: 81941537-4446-9c5a-6af3-25318396420d
* Content: [Build and run a C++ console app project](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=vs-2019)
* Content Source: [docs/build/vscpp-step-2-build.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-2-build.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-10-17 00:03
@mohowzeh 
I'm closing this, because I couldn't reproduce your issue. The document doesn't specifically mention that solution folders are created under *`%USERPROFILE%\source\repos\`* by most templates in Visual Studio 2019, but the path does appear in one of the images. In earlier versions of Visual Studio, the default location was in the user's *`Documents\Visual Studio 20XX\Projects`* folder. In either case, when you use the Windows Desktop Wizard template (Win32 Console Application in earlier versions) to create a console app, the build output directory depends on the configuration. In Debug builds, it's a folder named *`Debug`* under the solution folder, whether you choose to save the project and solution in the same folder or not. 
It's possible that some version of VS and some templates may create an intermediate directory named *`bin`*. The console app templates in VS 2015, 2017, and 2019 that I checked did not.

**Closed by corob-msft** 2020-10-17 00:03 UTC
Labels: not-a-doc-issue
