### ISSUE TITLE
Why does the buffer size parameter needs casting to unsigned? size_t is already unsigned!

### ISSUE THREAD

**Issue by Dirksche** [MicrosoftDocs/cpp-docs#440] opened 2018-09-21 08:35 UTC
This documentation states:
&gt; The size parameter is of type **unsigned**, not **size_t**. When compiling for 64-bit targets, use a static cast to convert **_countof** or **sizeof** results to the correct size.

But the `size_t` datatype is already `unsigned`. The MSDN documentation "Standard Types" (https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types?view=vs-2017) states for `size_t`:
&gt; unsigned __int64 or unsigned integer, depending on the target platform

Does it need to be casted to a 32-bit unsigned integer?
Does a cast to `unsigned` implies a cast of 64-bit datatypes to 32-bit when compiling for 64-bit systems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb0a71a-b940-e7e9-d6b2-a4d1ce0260b6
* Version Independent ID: 610f338f-1d30-7899-2df9-c0a1600ca7de
* Content: [sscanf_s, _sscanf_s_l, swscanf_s, _swscanf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(%22CORECRT_WSTDIO%2Fswscanf_s%22);k(swscanf_s);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-09-21 19:40
@Dirksche Your inference is correct; the cast is unnecessary when compiled for a 32-bit target architecture, but required when compiled for 64-bits. The note calls this out: the `size_t` result of `_countof` is 64 bits when compiled for a 64-bit target architecture, but the buffer size parameter must always be a 32-bit `unsigned` value, even when your code is compiled for 64-bits. (This implies a 2<sup>32</sup>-character limit on buffer sizes.) Since it's effectively a no-op in the 32-bit case, it's reasonable to use the cast unconditionally. That's why we show the cast in the examples, as a demonstration of good engineering practice for portable code.

I'm closing this issue as by design, but feel free to propose other wording if you think it would add clarity.

**Closed by corob-msft** 2018-09-21 19:40 UTC
