### ISSUE TITLE
Links are obsolete

### ISSUE THREAD

**Issue by roosslan** [MicrosoftDocs/cpp-docs#3431] opened 2021-10-05 19:11 UTC
Hi, 
weblinks on [activex-control-containers-using-controls-in-a-non-dialog-container.md](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/activex-control-containers-using-controls-in-a-non-dialog-container.md) now are with "CPP" not with "cpp":
so it waits for [CPP/activex-control-containers-using-controls-in-a-non-dialog-container_1.h](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/codesnippet/CPP/activex-control-containers-using-controls-in-a-non-dialog-container_1.h) instead of
[cpp/activex-control-containers-using-controls-in-a-non-dialog-container_1.h](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/codesnippet/cpp/activex-control-containers-using-controls-in-a-non-dialog-container_1.h) e.g. .

best regards

**Comment by corob-msft** [comment] 2021-10-05 20:07
@roosslan 
Thanks for the report. I don't see the effect you describe. It looks like the correct case appears in both the source document and in the [published document](https://docs.microsoft.com/en-us/cpp/mfc/activex-control-containers-using-controls-in-a-non-dialog-container?view=msvc-160). And as far as I know, the URIs are case-insensitive, so it should make no difference in page performance. I'm closing the issue as not repro, but I'm willing to revisit it if you can demonstrate that something is wrong.

**Closed by corob-msft** 2021-10-05 20:07 UTC
Labels: docs-experience, Closed - not repro

**Comment by corob-msft** [comment] 2021-10-06 08:50
Ah, thanks, I understand your report now. You're looking at the GitHub preview of our source, which doesn't support the markdown extensions we use to publish the content on docs.microsoft.com. I wouldn't say it is broken by design, but it doesn't matter to us if it works or not, because that's not what we expect people to read. The [official site](https://docs.microsoft.com/cpp) renders the images and other media correctly. It looks better. It lets you choose a theme, a language, and a product version. It has lots of useful navigation and search and feedback controls. So, we don't worry about issues in the preview. If a search engine leads you our GitHub preview, look nearby in the search results for a link to docs.microsoft.com, instead.
