### ISSUE TITLE
Should be "remoteMachine" NOT "remoteMachineName"

### ISSUE THREAD

**Issue by swinefeaster** [MicrosoftDocs/cpp-docs#4183] opened 2022-09-22 18:30 UTC
Should be "remoteMachine" NOT "remoteMachineName"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb710f7-0853-73c1-1792-a58a8471b7df
* Version Independent ID: 41619266-4f1a-6187-3f66-ca5f74326c95
* Content: [Tutorial: Debug a CMake project on a remote Windows machine](https://learn.microsoft.com/en-us/cpp/build/cmake-remote-debugging?view=msvc-170)
* Content Source: [docs/build/cmake-remote-debugging.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-remote-debugging.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-09-22 19:14
@swinefeaster 
Can you elaborate on which entries you think need to change, and which remote platform you're targeting? The [launch.vs.json schema](https://learn.microsoft.com/en-us/cpp/build/launch-vs-schema-reference-cpp?view=msvc-170) docs use "remoteMachineName" for ARM64 Windows remotes (as in this tutorial) and for Linux remotes, and that seems to work correctly in VS 2022 version 17.3.

**Comment by swinefeaster** [comment] 2022-09-22 19:17
When I use "remoteMachineName" in the laucnh.vs.json of my cmake project, it runs the app locally. If I change it to "remoteMachine", it prompts for the remote auth dialog.
________________________________

**Comment by corob-msft** [comment] 2022-09-22 19:43
@swinefeaster 
Is your remote an x64 Windows machine? I wouldn't necessarily expect cross-compiled code for ARM64 to run locally, unless maybe you're running x64 VS on ARM64 Windows in emulation mode.

@paulmaybee Checking for insights. Are the examples in the doc missing something significant, as for example [this Developer Community issue](https://developercommunity.visualstudio.com/t/Impossible-to-debug-a-cmake-project-on-a/10104354)?

**Comment by swinefeaster** [comment] 2022-09-22 20:35
cmake is not specific to ARM. we use cmake for win32 c++ apps on our team here.
________________________________

**Comment by paulmaybee** [comment] 2022-09-22 20:48
"remoteMachineName" is the correct field name when authoring launch.vs.json configurations. The json editor should pop-up a list of connection names when the opening " is entered for the remoteMachineName value.

**Comment by corob-msft** [comment] 2022-09-28 02:40
Given the developer input in our investigation, I'm marking the issue as closed by design. Thanks for the reporting.

**Closed by corob-msft** 2022-09-28 02:40 UTC
Labels: assigned-to-author, Closed - by design, product-team, customer-issue, cpp-cmake
