### ISSUE TITLE
Fatal Error C1853

### ISSUE THREAD

**Issue by SandyBittman** [MicrosoftDocs/cpp-docs#2534] opened 2020-10-15 04:42 UTC
[Enter feedback here]

I started getting this error for an unknown reason.  I did not find a solution on line so I took a wild shot at it.

I'm writing a "Market View" program to analyze the stock market for investing, of course the C++ windows program is called MarketView.exe.

The file it was complaining about was MarketView.pch, which I never touched, but on a long shot I merely renamed that file, in the debug directory to xMarketView.pch.  When I hit F5, everything recompiled, a new Marketview.pch file was created, and everything seems to be working again.

I would not merely delete your pch file, but try renaming it and see if Visual Studio will recreate it again for your.

PS: the old and new files are both exactly 7,798,784 bytes in size!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e119265-8152-3401-40cd-28ad29e9e6cf
* Version Independent ID: 15b66025-7e97-4225-80c7-965fdd6e7a6c
* Content: [Fatal Error C1853](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1853?view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1853.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1853.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-10-15 10:38
@SandyBittman 
Thanks for the report. I'm glad you dealt with the problem successfully. Changing the name of the PCH file is tantamount to deleting it as far as Visual Studio is concerned. It has no way to tell the file is still around under a different name. You should get similar results by cleaning your build. Odds are your issue was caused by some minor file corruption, which kept the PCH file from being read correctly. 
If the problem was caused by a bad sector on disk, it might persist as long as the PCH file used that location, so renaming the file would force a new disk location to be used. Unlikely, but possible.
I'm not seeing a clear reason to modify the documentation here, so I'm closing the issue.

**Closed by corob-msft** 2020-10-15 10:38 UTC
Labels: product-feedback
