### ISSUE TITLE
pipeArgs needs more details

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/cpp-docs#1973] opened 2020-03-11 23:29 UTC
Too much time have I wasted on trying to figure out what pipeArgs is and what are the meanings of its parameters. This document doesn't provide any useful information.
What is the debugInfo.remoteMachineId in pipeArgs? Is it the same as the top level one? I tried to put the same value in it but it doesn't work at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7a4e8b-d422-93b1-e042-55c2acbf8ef3
* Version Independent ID: 0d55f5d8-846e-3282-b580-9b7770053958
* Content: [Configure CMake debugging sessions in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=vs-2019#customize-debugger-settings)
* Content Source: [docs/build/configure-cmake-debugging-sessions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configure-cmake-debugging-sessions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-03-13 00:59
@esweet fyi, is this something you can clarify?

**Comment by esweet** [comment] 2020-03-13 01:03
I think you tagged the wrong person?

**Comment by corob-msft** [comment] 2020-03-13 21:21
@esweet Yes, my apologies. The reference was intended for @esweet431 but I hit Tab too quickly.

**Comment by esweet431** [comment] 2020-03-13 22:22
Sorry for the confusion. You don't need to manipulate debugInfo.remoteMachineName in pipeArgs - or any other parameters of the pipeArgs object - in order to debug. remoteMachineName (at the root level) is what you should be using to set the remote system you are deploying to and debugging on. pipeArgs *can* be used to export the DISPLAY variable or run a script/command before the execution of gdb, but those are both entirely optional.

**Comment by TylerMSFT** [comment] 2024-03-02 01:56
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Closed by TylerMSFT** 2024-03-02 01:56 UTC
Labels: doc-enhancement
