### ISSUE TITLE
Document is not well written or either not updated

### ISSUE THREAD

**Issue by abhisekmane98** [MicrosoftDocs/cpp-docs#4070] opened 2022-07-28 11:13 UTC
[Enter feedback herTo add a new configuration, select the configuration drop-down in the toolbar and choose Manage Configurations:e, this did not ope what was shown in Document I will add pic that open there. So how should I proceed further.]
![Screenshot (98)](https://user-images.githubusercontent.com/57854572/181491994-b2f0d5cf-515e-4ebe-8ef9-17a88c58916b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292b6ea2-afb0-8a77-7748-6d39286890ce
* Version Independent ID: 55816d6b-9600-c31c-01df-b53c2f185319
* Content: [Customize CMake build settings in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-150)
* Content Source: [docs/build/customize-cmake-settings.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/customize-cmake-settings.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-08-04 01:11
@abhisekmane98 

I'm sorry you're having trouble. I'm guessing the problem is that your project is not a CMake project. The Configuration Manager dialog is different for CMake projects, and the one in your screenshot is the Configuration Manager dialog for a .vcxproj project. It isn't possible to convert one project type to the other, so you'll have to recreate your project as a CMake project to get the integrated CMake experience in Visual Studio.

It also looks like you're using the documentation for Visual Studio 2017. If that's not the version you're actually using, the experience will also be different. To change the version of the docs to match your version of Visual Studio, use the **Version** control at the top of the content tree on the left.

Since this is apparently not a documentation issue, I'm closing it. Best of luck with your code.

**Closed by corob-msft** 2022-08-04 01:11 UTC
Labels: Closed - not a doc issue, customer-issue
