### ISSUE TITLE
Where is the 'exceptions thrown' documentation?

### ISSUE THREAD

**Issue by EddieBreeveld** [MicrosoftDocs/cpp-docs#406] opened 2018-08-31 08:45 UTC
I get an 'invalid parameter exception' thrown with some Korean characters with CStringA::MakeLower.  Where is the documentation for the exceptions that could be thrown thrown by these methods?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a9ec5a-f8e2-f739-1b39-74b4a775ee98
* Version Independent ID: c1eaf2d0-1cd3-25a1-c44d-3aae49be555b
* Content: [CStringT Class](https://docs.microsoft.com/en-gb/cpp/atl-mfc-shared/reference/cstringt-class?view=vs-2017)
* Content Source: [docs/atl-mfc-shared/reference/cstringt-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cstringt-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment] 2018-08-31 10:15
@EddieBreeveld I'm sorry you're having difficulty. There's no such explicit list, mostly because creating one is unworkable in practice. To create such a list for every member function, there would have to be an analysis of all the possible code paths that can throw an exception to some arbitrary depth. However, as it happens, the ATL library isn't very complicated, and it basically throws just four kinds of exceptions: for invalid parameters, out of memory, an HRESULT or system error code turned into an exception, and a generic failure exception. Possible invalid parameters are the usual suspects: null pointers and values out of range, perhaps zero or negative when they should be positive, or outside the bounds of a memory allocation.

In your case, you're in luck, because exceptions are trapped by the debugger, and you can usually see exactly what triggered an invalid parameter exception. Set a breakpoint right before the problem code and step through it to see what's going wrong. There's nothing special about Hangeul characters that would cause a problem, as long as you've defined either `_MBCS` or `_UNICODE` to indicate your string type. If you haven't, then I'd expect problems of all sorts when your code is compiled for ANSI and gets fed multibyte or Unicode characters. 

I'm closing this issue, because this seems like a support question, and not something we'd address in the documentation. If instead you think you've found an actual bug in the product, I recommend the **Help** > **Send Feedback** > **Report a Problem** menu in the IDE. It's the easiest way to bring something to the attention of the product engineering team.

**Closed by corob-msft** 2018-08-31 10:15 UTC

**Comment by rtischer8277** [comment] 2019-12-06 16:14
Are you suggesting that I should trap on every CString method call? Great that VS debugger catches these exceptions, but what about production code? There needs to be a workaround. For example, for ordinary ipv6 address like '2600:8806:2700:ddab:490f:c81e:479a:ccde' neither IsEmpty or GetLength work. To make matters worse, the errors seem to be non-deterministic. As an application programmer, not being able to trust these functions is unacceptable. Ok, I will report this as an error.

**Comment by corob-msft** [comment] 2019-12-06 22:20
@rtischer8277 
The library is decades old, and in use in millions of apps. It's unlikely you've exposed a library bug. What I'm suggesting is that you use the debugger to see where the bug is that causes the exceptions. In particular, I'd suggest using memory breakpoints to trap unexpected writes to your string buffers, and writes past the end. Another thing to check for is consistent use of the APIs for MBCS. It's not unusual for MBCS encoded text to run afoul of code that makes poor assumptions about character width and string length. It's easily the most common source of bugs in internationalized code. These issues lead to heisenbugs more often than not. The effect may appear long after the cause. Best of luck with your investigation.
