### ISSUE TITLE
Upgrade C++ projects from earlier versions of Visual Studio (does not work)

### ISSUE THREAD

**Issue by zfuller5** [MicrosoftDocs/cpp-docs#3653] opened 2022-01-13 20:41 UTC
This document does not appear true with my experience. I am trying to run a .dsw/.dsp (vc6 format) project on VS2022. A) If I try and open the project from the home page, .dsp/.dsw are not file types I can search for / open. B) According to this page, when I instead try opening the project file from the file explorer it opens the .dsp file but does not offer to upgrade the project to the current schema.

**Comment by corob-msft** [comment] 2022-01-14 01:36
@zfuller5

Visual C++ 6.0 is now nearly 24 years old and hasn't had an update since 2004. It's been out of extended support since 2008. We don't document anything about it anymore. Officially, [we don't support C++ project upgrades from versions older than Visual Studio 2010](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2022).

That said, I have it on good authority that upgrades should still work for `*.vcproj` files from Visual Studio versions before 2010. However, I don't think earlier project files like `.dsp` or `.dsw` files have been supported for some time. I haven't tried this myself, but I've heard that It's possible to upgrade your VC6 project if you do it in two steps. You'll need a copy of Visual Studio 2010 (or maybe even 2012), which I believe can upgrade VC6 projects to `*.sln` and `*.vcxproj` files. First, you'd upgrade your VC6 project to VS2010 (or 2012). Then you should be able to upgrade the upgraded project in Visual Studio 2022. You'll almost certainly need to make both source and library file changes in your new project to get the code to compile and build in VS2022.  There have been changes to header file names, function signatures, DLLs, and library files in the intervening decades that you'll have to fix. I can't assure you that this process will work, but I figure it's worth a try. The other way to deal with the issue is to copy just the source files into a brand-new project you create in VS2022. You'll have the same kinds of source issues to fix, but who knows, it might be less work overall.

Officially, we neither document nor support this process from VC6, so I'm closing your issue as not requiring a doc change. Best of luck with your upgrade.

**Closed by corob-msft** 2022-01-14 01:36 UTC
Labels: support-request, Closed - won't fix
