### ISSUE TITLE
Incorrect code sample for C4927

### ISSUE THREAD

**Issue by alexalexroro** [MicrosoftDocs/cpp-docs#281] opened 2018-06-10 13:33 UTC
The code sample does not generate warning C4927, it generates error C2440: error C2440: 'return': cannot convert from 'B' to 'A'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ff26eb-1c31-d4f3-622d-19161e65d894
* Version Independent ID: 81630e4b-df91-200c-31b6-dd83dff1deb1
* Content: [Compiler Warning (level 1) C4927](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4927#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4927.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4927.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-06-12 22:28
Thanks for reporting this issue. The product team does change the diagnostic output priority from time to time, so I'll take a look at what might actually cause C4927 in the latest version of the compiler.

**Comment by corob-msft** [comment] 2018-09-12 20:37
Now that I've taken a look at this again, the sample is in fact generating warning C4927 in VS2017 version 15.8. Perhaps there was an issue in a particular version of the compiler that's since been addressed. Since I can't reproduce the problem, I'm closing the issue.

**Closed by corob-msft** 2018-09-12 20:37 UTC
Labels: P2
