### ISSUE TITLE
2

### ISSUE THREAD

**Issue by 66558487878** [MicrosoftDocs/cpp-docs#3881] opened 2022-05-09 00:25 UTC
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by 66558487878** [comment] 2022-05-09 00:26
11

**Comment by corob-msft** [comment] 2022-05-09 20:19
@66558487878 
I'm sorry, I can't tell what the issue is from your description, so I'm closing it. If you'd like to clarify what's wrong, I can always reopen the issue. Thanks.

**Closed by corob-msft** 2022-05-09 20:19 UTC
Labels: Closed - not repro
