### ISSUE TITLE
Vectorizer C5002 reason code 1204

### ISSUE THREAD

**Issue by maxim-komlik** [MicrosoftDocs/cpp-docs#2780] opened 2021-02-16 21:15 UTC
I noticed that compiler emitted the following message during build:
`code.cpp(161) : info C5002: Loop not vectorized due to reason: "1204"`
I was not able to find any information about this reason code. I have described the issue in detail on [stackoverflow](https://stackoverflow.com/questions/66231946/what-does-c5002-1204-auto-vectorizer-reason-code-mean).
I'm using VS Community 2019 16.7.7 on Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2ca534-d8f2-9608-9ad5-6d1773195a69
* Version Independent ID: e2d87bb9-5f1c-ea08-8ce9-045072d87734
* Content: [Vectorizer and parallelizer messages](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/vectorizer-and-parallelizer-messages?view=msvc-160)
* Content Source: [docs/error-messages/tool-errors/vectorizer-and-parallelizer-messages.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/vectorizer-and-parallelizer-messages.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-02-17 00:48
@maxim-komlik 
Thanks for the report. This appears to be a duplicate of issue #2467, which has some additional info. An update should appear with the relevant info by tomorrow sometime.

**Closed by corob-msft** 2021-02-17 00:48 UTC
Labels: duplicate
