### ISSUE TITLE
Suggestion to clarify the language to avoid misunderstanding

### ISSUE THREAD

**Issue by captainhusaynpinguin** [MicrosoftDocs/cpp-docs#2632] opened 2020-12-03 19:40 UTC
[Enter feedback here]

I came across this page trying to learn C [prior knowledge in PHP, etc] and I believe there is some cause for misunderstanding on this page, so my recommendation is to change the language from:

**The loop-expression is evaluated after each iteration.**

to something along the lines of:

**The _loop-expression _ is executed as the last command in a loop.**

For example:

```
long wow;
    for (wow=0; wow <= 0; ++wow) {
    }
    printf("wow = %li \n", wow);
``` 

Will return "1" instead of "0".

PS. Thanks for the free tutorial though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c601d81-2503-f2ca-c6de-41080354e44d
* Version Independent ID: bd1b0ade-906f-6c9e-b2d7-fec51b088f54
* Content: [for Statement (C)](https://docs.microsoft.com/en-us/cpp/c-language/for-statement-c?view=msvc-160)
* Content Source: [docs/c-language/for-statement-c.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/for-statement-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-12-04 01:21
@captainhusaynpinguin 

Thanks for taking the time to write. The current wording is precise and intentional, but terse and at a relatively advanced reading level. Could you elaborate on what you find confusing? For example, we could say "The *loop-expression* is evaluated after each **_statement_** iteration **completes**" or "The *loop-expression* is evaluated after each iteration **of the _statement_**" to clarify. Would that help in understanding?

**Comment by captainhusaynpinguin** [comment] 2020-12-06 21:36
I  totally agree that it is precise and that's also why I was using this to help some friends, who are first year mechanical engineering students, with beginning C-language; In retrospect, I think, looking at it from a human brain's perspective who is unaware of how computers work, it looks obvious that if you set a limit for yourself, you won't exceed that limit; Especially if you are a machine and don't have desires/lusts/etc.

So, they were kind of treating this behavior as a "exception" that made them even more confused when mixed with `while` and negative iterations.

Whether this behavior-expectation is a cultural default or depends on other group-specific factors, I'm not confident about, but as much as possible, I rather prefer the low-level functionalities be explained in descriptive enough format that the distinction between human's default vs machine's default behavior is clear.

But again, one could also argue that your guide is written for individuals who are well-familiar with one or other programming language, if not C itself, so ... I agree, the conciser, the better. In which case I apologize for taking your time.

**Comment by corob-msft** [comment] 2020-12-07 22:16
Closing, as I'm biased toward inaction where there isn't a clear improvement to be made. Most of our C-language content dates to a time when people learned programming from books. This content was intended as a slightly more readable paraphrase of the C89 language standard, not as a tutorial. (That also tells you how old it is.) We're updating it a little as the compiler adds support for C11, and C17. We do want it to be useful for language learners, but we'd recommend a tutorial first, and then this content as a reference. And thanks for helping others to learn C.

**Closed by corob-msft** 2020-12-07 22:16 UTC
Labels: doc-enhancement
