### ISSUE TITLE
C3646 on Member Variable, not Function as Documented

### ISSUE THREAD

**Issue by TOtto-EclipseIR** [MicrosoftDocs/cpp-docs#3105] opened 2021-04-26 23:38 UTC
[Enter feedback here]
In ObjectResults::Item header file
        Quality mQuality;
generates the errors below

`Quality` is a Qt5 QMetaType
        Q_DECLARE_METATYPE(Quality);

Messages from MSVC2019 compiler:
D:\dev\INDI6\src\libs\InObjDet/ObjectResults.h(62): error C3646: 'mQuality': unknown override specifier
D:\dev\INDI6\src\libs\InObjDet/ObjectResults.h(62): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\dev\INDI6\src\libs\InObjDet/ObjectResults.h(33): error C2065: 'mQuality': undeclared identifier
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74dbeb20-6cf2-1d0c-d38e-843bc22917ae
* Version Independent ID: 8e693528-5343-45fe-a7e8-2e8a5ab83f8f
* Content: [Compiler Error C3646](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3646?view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c3646.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c3646.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-04-26 23:56
@TOtto-EclipseIR 
Sorry you're having trouble. When I see errors like this, I usually try the [`/P` (Preprocess to a file)](https://docs.microsoft.com/en-us/cpp/build/reference/p-preprocess-to-a-file?view=msvc-160) compiler option to see what the compiler is actually trying to compile. The cause is usually something simple, like a missing `#define` or `#include` directive, or even a missing semicolon somewhere above. 

Since your issue doesn't indicate anything is wrong with the documentation, I'm closing it. Docs feedback isn't a support channel for programming questions; for those, I recommend [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) instead. Best of luck.

**Closed by corob-msft** 2021-04-26 23:56 UTC
Labels: support-request
