### ISSUE TITLE
Please fix doco or analysis software.

### ISSUE THREAD

**Issue by thammr** [MicrosoftDocs/cpp-docs#1752] opened 2019-12-01 23:00 UTC
Can this function return success (0) but set pFile to 0. If so, why doesn't this document state this. If not PLEASE fix your buggy analysis code which claims that pFile can be 0 even if fopen_s returns 0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a2e737-afe6-a70d-8eb3-fe3a0aeda3e8
* Version Independent ID: 3a9bdb00-1d09-1b08-3dc3-029a6a0b16a2
* Content: [fopen_s, _wfopen_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/fopen-s-wfopen-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fopen-s-wfopen-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2019-12-02 08:17
@thammr 

I can't think of a way to get a successful return from `fopen_s` without also getting a pointer to a valid stream. Don't take my lack of imagination as proof it can't occur, though. Stuff can happen. It's good engineering practice to check every return value, including every out parameter, before use.

Sometimes you know things the code analyzer doesn't. Say you declare some variable without an initializer, or you initialize it to a default, such as zero. You then pass its address as an out parameter to some external function that sets it before you do anything else with it. Often the analyzer can't tell that's what's happening. It can't look inside that external function to see what happens with the pointer, or reference. It will warn you that you're using the variable before it's initialized, or that you're using a value that could still be whatever you initialized it to. It's not a bug in the analyzer, it's a consequence of the way separate compilation works. You can call code that's a black box as far as the analyzer is concerned. You can either ignore the warning, or you can code defensively, if redundantly, to quiet it. That's up to you.

I don't see an issue to fix here, so I'm closing this. If I've misunderstood what you're saying, let me know.

**Closed by corob-msft** 2019-12-02 08:17 UTC
Labels: not-a-doc-issue
