### ISSUE TITLE
Problem with explanatory diagram(s) - no annotations

### ISSUE THREAD

**Issue by Davi-Gray** [MicrosoftDocs/cpp-docs#4423] opened 2023-02-17 17:36 UTC
1) The diagram illustrating the parts of a lambda expression is duplicated.
2) Neither of the copies of the diagram actually includes annotation of what the numbers indicate. Nor does the surrounding text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 437be494-4752-c2de-a8c0-c4bc8563ddb4
* Version Independent ID: 51317bb8-4c01-146a-f1a7-eba0e54cb5e4
* Content: [Lambda expressions in C++](https://learn.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)
* Content Source: [docs/cpp/lambda-expressions-in-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/lambda-expressions-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**
![lambdaexpsyntax](https://user-images.githubusercontent.com/124840911/219727719-ab792030-67b9-42b3-96de-272bc689bf0e.png)

**Comment by corob-msft** [comment] 2023-02-17 20:02
@Davi-Gray 
Thanks for the report; the issue should be fixed soon. Closing it as a duplicate of #4419.

**Closed by corob-msft** 2023-02-17 20:02 UTC
Labels: Closed - duplicate
