### ISSUE TITLE
Missing documentation for UWOP_EPILOG and for another value of UNWIND_INFO::Version

### ISSUE THREAD

**Issue by FaerHack** [MicrosoftDocs/cpp-docs#4189] opened 2022-09-24 11:53 UTC
This page doesn't mention UWOP_EPILOG unwind operation and UNWIND_INFO::Version with a value of 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-170#chained-unwind-info-structures)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by namazso** [comment] 2022-11-26 13:18
duplicate of #3514

**Comment by TylerMSFT** [comment] 2024-02-27 00:04
Closing as duplicate.

**Closed by TylerMSFT** 2024-02-27 00:04 UTC
Labels: doc-enhancement, assigned-to-author, product-team
