### ISSUE TITLE
Quesion?

### ISSUE THREAD

**Issue by RobertChilewskiGit** [MicrosoftDocs/cpp-docs#2674] opened 2020-12-19 01:47 UTC
Is A Compiler "Error" really just Human Fault? I mean why not Specify this in the Documentation i never understood this for the
longest time i mean i thought i broke something but its just improper code Format :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2e558b-8ef0-5847-b7be-18dc550cb9dc
* Version Independent ID: eab2d939-7dcc-8de6-1801-9a986eecdff4
* Content: [Compiler Error C2360](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2360?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2360)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2360.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2360.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-12-19 08:58
@RobertChilewskiGit 
In a sense you did break something - you broke your program. The way we name code defects as compiler errors, fatal errors, and warnings, is just a convention. However, you're right, they don't mean the compiler has made a mistake. (It's possible for the compiler to do something wrong, which it can sometimes detect and report as an *internal* compiler error.) Almost all things reported as compiler errors are actually programmer errors. Generally speaking, a compiler fatal error means the problem was bad enough that compiler can't continue. A compiler error means something is wrong enough with the code that the compiler can't generate a program. A compiler warning means the code will still result in a program, but maybe one that doesn't work as intended. Our diagnostic messages try to be more polite than directly saying "you made a mistake," but that's what they mean.
We're not going to change this very old convention, so I'm closing your issue.

**Closed by corob-msft** 2020-12-19 08:58 UTC
Labels: doc-idea

**Comment by RobertChilewskiGit** [comment] 2020-12-19 15:28
Thanks, I was just wondering.
I overthink  it seems with all of this I Completely Understand Now need for the Compiler to Be rude ❤️.
________________________________
