### ISSUE TITLE
Still not clear with CRT and UCRT

### ISSUE THREAD

**Issue by CaryFan** [MicrosoftDocs/cpp-docs#336] opened 2018-07-11 07:45 UTC
Hello, I would like to see a package view of CRT before VS2015 and after VS2015 due to the so-called Great C Runtime refactoring. After reading this article, I guess, the new CRT consists of UCRT and the vcruntime libraries, am I right? MS recommends now the developers to upgrade their C programs to depend on UCRT after the great refactoring, right? I am asking because I am helping our team to upgrade development environement from VS2013 to VS2017 which jumps over VS2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment] 2018-08-20 20:55
@CaryFan I am closing this issue as a duplicate of #335. To answer your question, any code compiled with VS2015 or later must use the UCRT. Code compiled with earlier versions of Visual Studio must use the earlier version of the CRT. The section "What problems exist if an application uses more than one CRT version?" describes pitfalls that can occur when you mix and match CRT versions in the same executable.

**Closed** 2018-08-20 20:55 UTC
