### ISSUE TITLE
Add reminders for linker options.

### ISSUE THREAD

**Issue by Zero-Tang** [MicrosoftDocs/cpp-docs#2535] opened 2020-10-15 09:26 UTC
[Enter feedback here]
Please remind readers to leave linker entry point option as nothing/default to let linker set the entry point to mainCRTStartup so that command-line arguments would be parsed and pass to main function. Otherwise, command-line arguments would not be parsed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c5ec8f-dc90-d0bd-5aa5-1340ccc877c3
* Version Independent ID: 19646aca-3da3-14e8-ea9a-fcb3020cf51c
* Content: [main function and command-line arguments (C++)](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=vs-2019)
* Content Source: [docs/cpp/main-function-command-line-args.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/main-function-command-line-args.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-10-15 11:19
@Zero-Tang 
Thanks for writing in. I'm not convinced that someone with a problem caused by setting the [`/ENTRY`](https://docs.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol?view=vs-2019) linker option would look here for a solution. After all, nothing in this article suggests you try it, and it's not something you're likely to do by accident.

If you use the **`/ENTRY`** linker option, then we assume you've [read the relevant article](https://docs.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol?view=vs-2019), which explains what it does. That article says up front "It is recommended that you let the linker set the entry point so that the C run-time library is initialized correctly, and C++ constructors for static objects are executed." That'is exactly where I'd look for this information. If you do anything else, we assume you have a good reason, and you know what you're doing.

I'd rather not clutter this particular article with information that won't be relevant to most readers, so I'm closing the issue. However, if you can marshal a good argument for why the info belongs here specifically, I'm willing to reconsider it.

**Closed by corob-msft** 2020-10-15 11:19 UTC
Labels: doc-idea

**Comment by Zero-Tang** [comment] 2020-10-16 00:42
The ambiguity is that the "C run-time library" is quite a broad concept, and coincidentally I failed to realize command-line parsing is included in this initialization - I thought it was done during the creation of process. I would say it might be better `mainCRTStartup` being noted in this article, or the ambiguity of "the C run-time library is initialized correctly" being eliminated.
Plus, I admit nothing in that article suggested me try it, but I love to tweak around the options: I name the entry point however I like. Due to my prior ignorance of usage about `mainCRTStartup`, why do I not skip the "useless code" for a smaller code? That's why I fall into the caveat. I read this page, instead of the page of linker, because I thought my customized `/ENTRY` option was not the problem, as if this page were explicating why the argument does not appear in the way it is supposed to be.
So, may I say at least somewhere should be edited somehow so that other "me"s in future will not fall for this caveat?
