### ISSUE TITLE
Filter Delimiters

### ISSUE THREAD

**Issue by DavidPx** [MicrosoftDocs/cpp-docs#1859] opened 2020-01-20 16:42 UTC
I'm using the CFileDialog constructor and could only get the filter string to work using the null-terminator delimiter, not the pipe as stated in the documentation.

```
CFileDialog     m_dlgFile(
    TRUE, // File Open vs. File Save
    L"xlsx",  // Default extension
    NULL,  // Initial file name if desired
    OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST | OFN_NODEREFERENCELINKS,  // Flags
    L"Excel Worksheets (*.xls;*.xlsx)\0*.xls; *.xlsx\0All Files (*.*)\0*.*\0", // Filter
    m_hWnd // Parent window
);
```

I'm building in VS19 with the 142 platform toolset.  WTL 10.0.9163.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86e2a5b-600c-6514-da7e-dd3c690fee0e
* Version Independent ID: d014df1a-8e49-85ae-589e-f4ec84f714bd
* Content: [CFileDialog Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cfiledialog-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cfiledialog-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cfiledialog-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-01-21 01:22
@DavidPx 
Eyeballing the implementation in *atlmfc\\src\\mfc\\dlgfile.cpp* around line 92, it looks like pipe characters ought to work, and be translated to nulls internally in MFC code. I'd be really surprised if this has changed in the last couple of decades. You ought to be able to step into the constructor code in the debugger and see what's happening there. If you're using MFC and see unexpected behavior with the pipe characters in the filter string when you step through the constructor's null conversion in the debugger, let me know, because this is the sort of issue to bring up on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html).

On the other hand, if you happen to be using the MFC docs but you're really writing WTL code, then yes, you'll need to use nulls. WTL doesn't do any translation for you.

**Comment by corob-msft** [comment] 2020-01-21 10:52
@DavidPx 
I missed the last bit of your complaint previously, where you explicitly list WTL. That's what I was asking about, so you don't need to answer. The MFC docs don't cover WTL, so I'm closing the issue.

**Closed by corob-msft** 2020-01-21 10:52 UTC
Labels: not-a-doc-issue

**Comment by DavidPx** [comment] 2020-01-21 16:01
Ah, my apologies for submitting this issue.  I found the doucmentation by searching for the class & function name, not noticing the difference in library.
