### ISSUE TITLE
Links in C++ 2015 redistributable EULA are broken

### ISSUE THREAD

**Issue by aasmundbo** [MicrosoftDocs/cpp-docs#236] opened 2018-05-16 11:00 UTC
The following link in the C++ 2015 redistributable EULA redirects to a MicrosoftDocs page which is a 404. 
- http://go.microsoft.com/fwlink/?LinkID=523763&clcid=0x409

It would be nice if the redirect is corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637a643b-3eb6-8a64-4979-ccfc07822681
* Version Independent ID: 86434874-40d2-d1d0-5551-a60620fad426
* Content: [Redistributing Visual C++ Files](https://docs.microsoft.com/en-us/cpp/ide/redistributing-visual-cpp-files)
* Content Source: [docs/ide/redistributing-visual-cpp-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/redistributing-visual-cpp-files.md)
* Service: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-05-16 22:17
Thanks for reporting this. This particular issue appears to effectively be a duplicate of issue #235, since the same fix has fixed it.

**Closed by corob-msft** 2018-05-16 22:17 UTC
Labels: doc-bug, duplicate
