### ISSUE TITLE
The MFC Help page for CWnd class is broken - won't load at all.

### ISSUE THREAD

**Issue by simonx222** [MicrosoftDocs/cpp-docs#4779] opened 2023-10-24 09:09 UTC
The help page for the MFC class CWnd is broken. See [https://learn.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=msvc-170](https://learn.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=msvc-170). It hangs every time I try and open it. This is probably the most important MFC Help page and it hasn't been working at all for ages. I get a "Page Unresponsive" error message every time I try and open it.  I tried clicking 'Wait' when I got the page unresponsive error message. After doing this twice I got a screen that said: "Aw, Snap! Something went wrong while displaying this webpage. Error code: Out of Memory".

I use this page all the time - or would if it worked.

**Comment by orcmid** [comment] 2023-10-24 15:30
See existing issue #4680 for some mitigation alternatives

**Comment by TylerMSFT** [comment] 2024-01-10 22:09
Closing this as a dupe of #4680  It's on my list to look at but will be a bit before I can get to it.

**Closed by TylerMSFT** 2024-01-10 22:09 UTC
