### ISSUE TITLE
Exception or Null...

### ISSUE THREAD

**Issue by dcorbin-wintellect** [MicrosoftDocs/cpp-docs#3913] opened 2022-05-20 14:09 UTC
The standard states: "throw bad_alloc", and most of the article agrees... EXCEPT "Handling Insufficie3nt memory" which shows a null return...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c874a84-386c-9e1d-5fb8-184bf7832c68
* Version Independent ID: a3f2112a-9314-85e8-51db-90f945e8d5f4
* Content: [new and delete operators](https://docs.microsoft.com/en-us/cpp/cpp/new-and-delete-operators?redirectedfrom=MSDN&view=msvc-170)
* Content Source: [docs/cpp/new-and-delete-operators.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/new-and-delete-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-05-26 04:58
@dcorbin-wintellect Thanks for the report. It just goes to show what sticks around in a thirty-something year old document. The article has some expansion on the possibilities now.

**Comment by dcorbin-wintellect** [comment] 2022-05-26 11:28
However, this particular section is misleading. The reader can look at *just this part* copy/paste the code and believe that returning null will be the default operation….

I am speaking from DIRECT EXPERIENCE with programmers who are working in C++ [but do not have a strong background].

I believe *this sample* needs to be annotated directly in inline with the requirement that explicit steps need to be taken to have a null return rather than an exception as mandated by the standard.

***@***.***


***@***.***
***@***.***

**Comment by corob-msft** [comment] 2022-05-26 22:34
@dcorbin-wintellect 
Apologies, I thought this article showed my updates when I closed the issue, but clearly my update hasn't been published yet. I'll follow up there and see what the issue is.

**Comment by corob-msft** [comment] 2022-06-01 08:32
The content has been published, so now it really is fixed. Closing again.

**Closed by corob-msft** 2022-06-01 08:32 UTC
Labels: doc-enhancement, Closed - fixed
