### ISSUE TITLE
omp_set_dynamic documentation is misleading

### ISSUE THREAD

**Issue by MLanghof** [MicrosoftDocs/cpp-docs#997] opened 2019-05-09 09:28 UTC
I understand that the current [OpenMP documentation for Visual C++](https://docs.microsoft.com/en-us/cpp/parallel/openmp/openmp-c-and-cpp-application-program-interface?view=vs-2019) is just a reproduction of the OpenMP 2.0 standard. However, it would be extremely helpful to also document how and where the implementation might not follow the letter or spirit of the standard.

The particular case I am concerned about pertains to [omp_set_dynamic](https://docs.microsoft.com/en-us/cpp/parallel/openmp/3-run-time-library-functions?view=vs-2019#317-omp_set_dynamic-function) and is described in detail at https://stackoverflow.com/q/56055959/9528746. In short, the OpenMP standard clearly intends the effects of `omp_set_dynamic` to be observable through `omp_get_num_threads`, yet this is not the case in Visual C++.

Is there a way to clarify this so that developers consulting the Visual C++ documentation are not misled (like I was)? For example, through the introduction of a "Visual C++ specific" section?

**Comment by corob-msft** [comment] 2019-05-09 19:52
@MLanghof 
That's a good suggestion. The question to answer first is: is the difference in behavior intentional, or a bug? For that, you must go to Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site and ask. This sounds like a bug to me. Our policy generally is to document *intentional* implementation specifics, not our bugs. While I don't know how often the OpenMP library updates go out, I know there's work going on in them. If you report this, I think it's likely to get fixed, since I can't imagine anyone would have code that breaks because it relies on the current behavior.

There's an easy way to report bugs like this one, built right into Visual Studio. Go to the **Help** menu, select **Send Feedback** > **Report a Problem**, and fill out a new problem report. Your report will be seen by the product developers who can do something about it. Make sure you include a description of what you're trying to do, all the steps you took, and what didn't work the way you expected. Any follow-up will be on the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site.

As a likely product bug, not a doc bug, I'm going to close this issue here. In the event that this is not a bug and is an intentional implementation decision, then please come back here and reopen this issue, and we'll do something much like what you suggest.

**Comment by mikeblome** [comment] 2019-05-09 20:10
@MLanghof  Thanks for the feedback. There is actually a doc issue here where we should call out  MSVC-specific behavior. We're not exactly deviating from the standard because as it says, the default behavior is implementation-defined:

“The default for the dynamic adjustment of threads is implementation-defined. As a result, user codes that depend on a specific number of threads for correct execution should explicitly disable dynamic threads. Implementations aren't required to provide the ability to dynamically adjust the number of threads, but they're required to provide the interface to support portability across all platforms.”

For MSVC this is also true and we'll update the docs:  “the current support of the two APIs are only at on/off level. A zero-valued input parameter disables multi-threading and nesting, respectively. A non-zero input parameter means the current number of threads (either from default value or previous user-defined via omp_set_num_threads API or environment variables) are used. ”

**Comment by MLanghof** [comment] 2019-05-09 21:45
Thank you for the responses!

@mikeblome I'm not sure we are on the same page...

> “The default for the dynamic adjustment of threads is implementation-defined. As a result, user codes that depend on a specific number of threads for correct execution should explicitly disable dynamic threads."

I explicitly call `omp_set_dynamic(1)` (or `omp_set_dynamic(0)`), so the default should not matter. Could you clarify?

> "Implementations aren't required to provide the ability to dynamically adjust the number of threads, but they're required to provide the interface to support portability across all platforms.”

MSVC (empirically) does provide the ability to dynamically adjust the number of threads. This is further supported by the standard saying "If the implementation doesn't implement dynamic adjustment of the number of threads, [`omp_get_dynamic`] always returns 0", while `omp_get_dynamic` returns `1` after calling `omp_set_dynamic(1)` on MSVC.

> “the current support of the two APIs are only at on/off level. A zero-valued input parameter disables multi-threading and nesting"

`omp_set_dynamic(0)` is not supposed to disable multi-threading or nesting, so this has to refer to some other part of the API - I assume to `omp_set_num_threads` and `omp_set_nested`? Sorry if I'm missing the context here, but I'm lost.

**Comment by hoyMS** [comment] 2019-05-10 16:44
@MLanghof  @mikeblome The input parameter to omp_set_dynamic as of now does not affect the threading policy with the implementation in MVSC. `omp_set_dynamic(0)` is supposed to turn of dynamic threading and `omp_set_dynamic(1)` is supposed to limit the number of threads to be 1. Neither of them really changes the thread number. In other words, `omp_get_num_threads` will always return the default thread number or what user has defined. **We should docuemnt this**.  What is different between `omp_set_dynamic(0)` and `omp_set_dynamic(1)` in current implementation is that, `omp_set_dynamic(0)` turns off dynamic threading so that the existing team of threads can be reused for the following parallel region. While `omp_set_dynamic(1)` turns on dynamic threading even if the thread nubmer is non honored, the existing team of threads will be trashed and a new team of the same number of threads are created and used for upcoming paralle region. This can be improved by just reusing the existing thread team so there won't be a performance gap between `omp_set_dynamic(0)` and `omp_set_dynamic(1)`. We should also document this for users' awareness.

**Comment by mikeblome** [comment] 2019-05-13 21:15
@MLanghof thanks for the feedback. Documentation has been updated and the fix should appear in a day or so.

**Closed by mikeblome** 2019-05-13 21:15 UTC
Labels: doc-enhancement, product-feedback
