### ISSUE TITLE
unfinished

### ISSUE THREAD

**Issue by terry-madsen-sage-com** [MicrosoftDocs/cpp-docs#3885] opened 2022-05-10 15:58 UTC
Nice outline, did someone forget to add the content (eg. pointers to samples)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23e79e5-af85-ef5e-fd28-b50841ee986e
* Version Independent ID: 55f78549-5f79-d09d-b631-19cafec6389e
* Content: [Macros and NMAKE](https://docs.microsoft.com/en-us/cpp/build/reference/macros-and-nmake?view=msvc-170)
* Content Source: [docs/build/reference/macros-and-nmake.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/macros-and-nmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-05-10 22:09
@terry-madsen-sage-com 
There aren't separate articles for samples to link to here. Any examples of NMAKE macros would be found in the individual articles below this introduction. As we don't have the resources to create additional NMAKE samples, I'm closing the issue as by design.

**Closed by corob-msft** 2022-05-10 22:09 UTC
Labels: doc-idea, Closed - by design
