### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by binhla** [MicrosoftDocs/cpp-docs#3897] opened 2022-05-16 04:18 UTC
Why this page is **Create a traditional Windows Desktop application** but select **Windows Desktop Wizard** instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-150)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by MSDN-WhiteKnight** [comment] 2022-05-16 09:35
And what's funny about it? The Windows desktop Wizard can actually be used to create a traditional desktop application. Did you mean that the article should demonstrate how to create it manually from empty project, instead of using wizard?

**Comment by corob-msft** [comment] 2022-05-16 22:32
@binhla 
We could use the Windows Desktop Application template instead of the Windows Desktop Wizard with an empty set of source files, but then we would have a different set of things to explain. The Windows Desktop Application template does more stuff, but it's mostly Windows App stuff, which we generally leave to the Windows documentation rather than try to cover in the C++ docs. We could also start from scratch with an Empty Project template, but then we'd spend a bunch of time setting properties before getting into the code. The Windows Desktop Wizard template sets those properties for us. The procedure we've chosen is a reasonable compromise that lets us focus on creating the code for a simple Win32 app without too much distraction or complexity.

Does this answer your question, or was there something more specific you'd like to have explained?

**Comment by corob-msft** [comment] 2022-05-21 00:10
Closing as by design.

**Closed by corob-msft** 2022-05-21 00:10 UTC
Labels: Closed - by design
