### ISSUE TITLE
This issue is about pages 26 and 27 of the `.pdf` file obtained after downloading it from "C/C++ projects and build systems in Visual Studio.pdf" which was generated using the MS corresponding site. 

### ISSUE THREAD

**Issue by jabelloc** [MicrosoftDocs/cpp-docs#4311] opened 2022-11-30 12:26 UTC
I have pages 26 and 27 of the alluded document in the title, copied as a `.pdf` document in my One Drive, containing my observations about the issue, **which shows up only in a `.pdf` document**. But I can't insert a link to this document here, neither can I copy the two pages to this write up.  How should I handle this problem?

**Comment by corob-msft** [comment] 2022-11-30 13:07
@jabelloc 
Let me guess: The issue is that you see the content for VS 2019 and later followed by the content for 2017 in the [Visual Studio projects - C++](https://learn.microsoft.com/cpp/build/creating-and-managing-visual-cpp-projects) article, in the **Create a Visual Studio C++ project** section. In the online version, the content that's displayed depends on the setting of the **Version** control above the list of articles on the left. There is no such control for the PDF version, so you get everything, without any indication of which version the various content sections apply to. You just see the numbered steps start over.

I don't know how to fix this issue. It's a problem with the way the PDF files are generated, which is done separately from the content rendering in HTML. There's only one PDF file link, and it doesn't switch between versions. Adding @herohua for insight.

**Comment by corob-msft** [comment] 2022-11-30 21:46
@jabelloc 
The PDF files aren't generated after each edit to the content. It's a manual process. We usually only generate them once or twice per major release, so differences can accumulate.

**Comment by TylerMSFT** [comment] 2023-04-18 21:53
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, how old it is, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.

**Closed by TylerMSFT** 2023-04-18 21:53 UTC
Labels: docs-experience
