### ISSUE TITLE
That Note is Misleading, for a proper WIN32 program, SEH is necessary

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#4290] opened 2022-11-13 18:54 UTC
![image](https://user-images.githubusercontent.com/145155/201545952-9725d661-6e32-4283-a8bf-5645126bcf73.png)

There is no way to catch any of the following, inside win32 program **not** using SEH. Regardless of the language used C or C++.

```c
STILL_ACTIVE                      
EXCEPTION_ACCESS_VIOLATION        
EXCEPTION_DATATYPE_MISALIGNMENT   
EXCEPTION_BREAKPOINT              
EXCEPTION_SINGLE_STEP             
EXCEPTION_ARRAY_BOUNDS_EXCEEDED   
EXCEPTION_FLT_DENORMAL_OPERAND    
EXCEPTION_FLT_DIVIDE_BY_ZERO      
EXCEPTION_FLT_INEXACT_RESULT      
EXCEPTION_FLT_INVALID_OPERATION   
EXCEPTION_FLT_OVERFLOW            
EXCEPTION_FLT_STACK_CHECK         
EXCEPTION_FLT_UNDERFLOW           
EXCEPTION_INT_DIVIDE_BY_ZERO      
EXCEPTION_INT_OVERFLOW            
EXCEPTION_PRIV_INSTRUCTION        
EXCEPTION_IN_PAGE_ERROR           
EXCEPTION_ILLEGAL_INSTRUCTION     
EXCEPTION_NONCONTINUABLE_EXCEPTION
EXCEPTION_STACK_OVERFLOW          
EXCEPTION_INVALID_DISPOSITION     
EXCEPTION_GUARD_PAGE              
EXCEPTION_INVALID_HANDLE          
EXCEPTION_POSSIBLE_DEADLOCK       
CONTROL_C_EXIT                    
```
SEH is critical for WIN32 programs handling the above exceptions. That is also why one can build the entire MS STL without CPP unwinding aka "c++ exceptions". 

MS STL without C++ exceptions is also necessary for programs using the `/kernel` cl.exe switch. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca5dfade-e224-32b4-919a-1e4f0c7b87ac
* Version Independent ID: 00702e1e-21c9-3520-ebec-53ff75dbb8f5
* Content: [try-except statement](https://learn.microsoft.com/en-us/cpp/cpp/try-except-statement?view=msvc-170)
* Content Source: [docs/cpp/try-except-statement.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/try-except-statement.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-11-14 20:15
@DBJDBJ 

It's not an exaggeration to say that we rely on our readers' abilities to know when our advice doesn't apply to them. Your issue shows that our confidence is justified.

While I'd take issue with the assertion that you can't catch the exceptions you listed with a C++ exception handler, I admit you probably wouldn't want to. Most of them shouldn't be handled at all. They should be treated as immediately fatal. The ones that aren't immediately fatal are generally translated into something useful on your behalf by the runtime or libraries (e.g. the EXCEPTION_INT_*, EXCEPTION_FLT_*, and EXCEPTION_GUARD_PAGE ones) and don't need structured exception handlers. 

The note has an implicit assumption you're writing for the application environment, and that you want to write code in a portable way. If you're writing code without library or runtime support, and especially *without exception support*, then we also assume you'll realize that the note doesn't apply to you, as you did. If we were to add a statement saying the note doesn't apply in certain cases, and listed each one, that's adding extra verbiage that everyone would have to read and evaluate in a fair number of such notes. It's an extra cognitive load cost I'd rather not impose on the bulk of our readers for whom the exceptions (pun intended) don't apply.

Absent a compelling argument otherwise, I'm inclined to close the issue as by design. I'm willing to entertain suggestions, though.

**Comment by DBJDBJ** [comment] 2022-11-14 22:19
# `SEH != C++ exceptions`

Whichever philosophy curtain one tries to hang in front of  SEH.  

Dear  @corob-msft, your audience is not a coherent group of C++ users, I suggest passing the C++ messages to the C++ audience.

**Comment by corob-msft** [comment] 2022-11-15 05:44
> I am assuming nobody has to be told, not to use SEH in case standard C++ is a requirement.
You'd think so, but that would be wishful thinking. That's why this note was added to the docs. It's the same reason much of the SEH documentation has a paragraph explaining the distinction between SEH and C++ exceptions. It's not programmers like you that need this information.

> SEH has nothing to do with standard C++. 
Not with the C++ standard, but it does have a fair amount to do with the MSVC implementation of C++ exceptions. MSVC built its C++ exception handling mechanism around the Windows Structured Exception facility, so C++ exception handling is basically a special case of SEH with injected code for passing exception parameters and cleaning up locals. As noted elsewhere, you can trap SEH exceptions in Microsoft C++ using the /EHa option with a `catch(...)` statement. Not saying you should, only that you can.

There's a more detailed explanation of when and why we recommend Standard C++ exceptions in [Structured and standard C++ exception handling](https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170#structured-and-standard-c-exception-handling). This note is an echo of that one.

**Closed by corob-msft** 2022-11-15 05:44 UTC
Labels: doc-idea, Closed - by design

**Comment by DBJDBJ** [comment] 2022-11-15 15:01
I can be stubborn too :)

> Specifying /EHa and trying to handle all exceptions by using catch(...) can be dangerous. 

Should say: trying to handle SEH using `catch( ... )`

> In most cases, asynchronous exceptions are unrecoverable and should be considered fatal. 

Unless you are writing a `/kernel` code when SEH are irreplaceable

> Catching them and proceeding can cause process corruption and lead to bugs that are hard to find and fix.
> 

Please look into how to create and use minidump. 

> Even though Windows and Visual C++ support SEH, we strongly recommend that you use ISO-standard C++ exception handling (/EHsc or /EHs). 

That is misleading. There are programs (hint `/kernel`) where SEH have no substitute. Even MS STL compiles and is usable in `/kernel` situations. ISO-standard C++ exception handling is for  ISO-standard C++ code.

> It makes your code more portable and flexible. 

Ditto, that is meaningless if and when one does not want code to be portable. And the "flexible" attribute is just plain annoying. Code has to address the requirements, full stop.

> There may still be times you have to use SEH in legacy code or for particular kinds of programs.

Excellent. Why not start the note with this sentence?

> It's required in code compiled to support the common language runtime ([/clr](https://learn.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=msvc-170)), for example. For more information, see [Structured exception handling](https://learn.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-170).
> 

Good, but again Win32 C code or Win32 C code with a `/kernel`  is not mentioned. Why? 

> We recommend that you never link object files compiled using /EHa to ones compiled using /EHs or /EHsc in the same executable module. If you have to handle an asynchronous exception by using /EHa anywhere in your module, use /EHa to compile all the code in the module. You can use structured exception handling syntax in the same module as code that's compiled by using /EHs. However, you can't mix the SEH syntax with C++ try, throw, and catch in the same function.

You got your "nickers in a twist" in that paragraph :) Again assuming that everyone all the time and everywhere does C++.  The above paragraph is irrelevant for pure C code on Windows.

> you can't mix the SEH syntax with C++ try, throw, and catch in the same function.

in any case cl.exe will not let you do so.

WIN32 libraries are all emitting [SEH](https://patents.google.com/patent/US6247169B1/en). For a reason.
