### ISSUE TITLE
How to avoid error C2081?

### ISSUE THREAD

**Issue by AndersBillLinden** [MicrosoftDocs/cpp-docs#2709] opened 2021-01-18 17:29 UTC
Adding the command line switch /c does not seem to get rid of the error.
Did I misunderstand something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d25c20c-e0b4-f5dc-d9ac-64a8d96a8ba7
* Version Independent ID: ca6fe1a4-3782-17a1-cfa6-933dd5468388
* Content: [Compiler Error C2081](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2081?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2081)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2081.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2081.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-01-18 17:47
@AndersBillLinden 

Your question confused me until I read the examples in the error article. The [`/c`](https://docs.microsoft.com/en-us/cpp/build/reference/c-compile-without-linking?view=msvc-160) compiler option has nothing to do with resolving the error, it just allows you to compile a source file to an object file without linking it to create an executable. If you compiled the example without **`/c`**, it would fail, since there's no `main` function. (This is also true of the first example, so it should have the same comment.) The important part of the second example that solves the problem is providing a type for the `j` parameter. That's the fix for what the error message is about. C2081 is usually caused by a typo, such as a missing comma in a parameter list, or by leaving out a type as in the first example, or by failing to `#include` a header file where a type you've used is defined.

**Comment by AndersBillLinden** [comment] 2021-01-18 18:09
So there is no way making the compiler tolerant with names in formal parameter lists?

**Comment by corob-msft** [comment] 2021-01-18 18:28
@AndersBillLinden 
I'm not sure I understand what you're asking. In a function declaration, parameter types are required, but names are optional. In a function definition, you'll need both types and names for the parameters you use. I don't think it's ever been the case that you could supply names without types for parameters in a declaration. However, once upon a time, C didn't require parameter types for a forward declaration, just a function name. The compiler doesn't accept those old forms, and will complain if a forward declaration doesn't match its usage or definition.

**Comment by corob-msft** [comment] 2021-01-18 18:37
Perhaps the confusion arises because within a function, you can define multiple variables of the same type without repeating the type, as in

`int a, b, c;`

while if you want to pass three integer parameters, each parameter must have an explicit type, as in

`int func(int a, int b, int c);`

which you could also forward declare as

`int func(int, int, int);`

if you wanted to, because the names are optional in the declaration, but you can't declare it as

`int func(int a, b, c);`

because `b` and `c` will be interpreted as type names, which likely won't be found and weren't your intent anyway.

**Comment by AndersBillLinden** [comment] 2021-01-18 19:18
What I am asking is if there is some command line switch to the compiler so it will not treat C2081 as an error.

**Comment by corob-msft** [comment] 2021-01-18 21:12
@AndersBillLinden 
No. The compiler emits an error when it can't create executable code from the source file. If something is wrong but it's still possible to create executable code, the compiler emits a warning instead. That's why there are command-line switches to disable warnings, but not errors.

**Comment by AndersBillLinden** [comment] 2021-01-19 12:16
But there are command line switches to change language compatibility, isnt there?

**Comment by corob-msft** [comment] 2021-01-19 12:34
@AndersBillLinden 
Do you have an example declaration that shows me what you're trying to do? I'm not aware of any version of the C or C++ language standard that lets you just name parameters in a function declaration without providing associated types.

**Comment by AndersBillLinden** [comment] 2021-01-19 14:01
````
WINBASEAPI WINBOOL WINAPI InitializeContext (PVOID Buffer, DWORD ContextFlags, PCONTEXT *Context, PDWORD ContextLength);
````

name in formal parameter list illegal

`PCONTEXT` are marked red.

But maybe it never got defined in winnt.h because of some preprocessor directive.

(Maybe its only my knowledge thats buggy).

**Comment by AndersBillLinden** [comment] 2021-01-19 14:02
Its an entirely different error than the one described on that page, but its still labeled C2081.

**Comment by corob-msft** [comment] 2021-01-19 22:35
@AndersBillLinden 
If you're using Visual Studio, you can hover over the symbols with red squiggles underneath, and see the IntelliSense error in a pop-up. It sounds like `PCONTEXT` is undefined, which is why you get error C2081. I'm afraid you'll have to do some detective work to find out why. 
The error documentation is meant to be generic, and can't possibly cover every way you could get an error. I don't think this case rises to the level of needing its own documentation, especially since you'll get warnings before this error that point you toward a solution, such as the red squiggles. That's why I'm closing the issue. Good luck with your program!

**Closed by corob-msft** 2021-01-19 22:35 UTC
Labels: doc-enhancement
