### ISSUE TITLE
mention that commands should be launched not from the root directory but one level above

### ISSUE THREAD

**Issue by GerardteM** [MicrosoftDocs/cpp-docs#3081] opened 2021-04-11 19:37 UTC
It took me some time before I had figured out that the commands to launch vcpkg integrate install should not be run from the root directory, but one level above with the command vcpkg\vcpkg integrate install This also applies to the command bootstrap-vcpkg.bat 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b976f77-ad03-e4df-2110-547661be152d
* Version Independent ID: 1733f352-20e0-d14a-c8dc-28c19909ed35
* Content: [Install vcpkg on Windows, Linux, and macOS](https://docs.microsoft.com/en-us/cpp/build/install-vcpkg?view=msvc-160&tabs=windows)
* Content Source: [docs/build/install-vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/install-vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-04-12 20:18
@GerardteM 
The commands should work whether you're in the vcpkg root directory or elsewhere, if you invoke vcpkg with the correct path. What kind of problem did you have that was solved by invoking vcpkg from the directory above?

**Comment by GerardteM** [comment] 2021-04-12 20:39
I got a message that a command cannot be executed from the directory where
the command is located. Running it from the directory above worked.

thanks for the reply,

regards

Gerard te Meerman
Klooslaan 12, 9721XN Groningen
smartphone : 0627580835
thuis
0505256544


Op ma 12 apr. 2021 om 22:18 schreef Colin Robertson <
***@***.***>:

**Comment by corob-msft** [comment] 2021-04-12 21:02
@GerardteM 
I haven't seen this particular issue on Windows. I imagine it could happen if directory execute permissions aren't set on another platform. Which platform are you using, and what was the text of the error message?

**Comment by GerardteM** [comment] 2021-04-13 18:44
Hi Colin,

I am using windows10 professional.

I include my output: it is not that you should use vcpkg, but .\vcpkg

I hope this clarifies my comment

regards

Gerard te Meerman



PS C:\vcpkg_root\vcpkg> vcpkg
vcpkg : The term 'vcpkg' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ vcpkg
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (vcpkg:String) [],
CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command vcpkg was not found, but does exist in
the current location. Windows PowerShell does not load commands from the
current location by default. If you trust this command, instead type:
".\vcpkg". See "get-help about_Command_Precedence" for more details.
PS C:\vcpkg_root\vcpkg> .\vcpkg
PS C:\vcpkg_root\vcpkg> .\vcpkg help
PS C:\vcpkg_root\vcpkg> bootstrap-vcpkg.bat
bootstrap-vcpkg.bat : The term 'bootstrap-vcpkg.bat' is not recognized as
the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and
try again.
At line:1 char:1
+ bootstrap-vcpkg.bat
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bootstrap-vcpkg.bat:String)
[], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command bootstrap-vcpkg.bat was not found, but
does exist in the current location. Windows PowerShell does not load
commands from the current location by default. If you trust this command,
instead type: ".\bootstrap-vcpkg.bat". See "get-help
about_Command_Precedence" for more details.
PS C:\vcpkg_root\vcpkg> .\bootstrap-vcpkg.bat
Downloading
https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe
-> C:\vcpkg_root\vcpkg/vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with
-disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\vcpkg_root\vcpkg>

Klooslaan 12, 9721XN Groningen
smartphone : 0627580835
thuis
0505256544


Op ma 12 apr. 2021 om 23:02 schreef Colin Robertson <
***@***.***>:

**Comment by corob-msft** [comment] 2021-04-13 22:25
@GerardteM 

I see where the problem is. You're using PowerShell, while the examples are written for the CMD.EXE command shell. PowerShell isn't as commonly used, so it's not what we describe in our docs by default. It's a little annoying that the behavior is different.

As a PowerShell user, if the text specified that "Command Prompt window" meant a CMD.EXE shell, would you have known what to do to change the commands for your PS prompt?

**Comment by GerardteM** [comment] 2021-05-14 20:56
likely

**Comment by corob-msft** [comment] 2021-05-14 21:04
I'm closing the issue, since the vcpkg docs have moved to vcpkg.io.

**Closed by corob-msft** 2021-05-14 21:04 UTC
Labels: Investigating, needs-more-info, waiting for response
