### ISSUE TITLE
How to install only the command line tools?

### ISSUE THREAD

**Issue by Foadsf** [MicrosoftDocs/cpp-docs#3777] opened 2022-03-16 14:15 UTC
I am trying to follow the instructions on [this page](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#feedback) to install only the command line tools and compilers. I want to write C and Assembly code and use the Nmake to run MakeFile. I don't need the MSV C/C++ IDE. 

The page directs me to [this other page](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) where I can download the **Build Tools for Visual Studio 2022**:

> ![2022-03-16 13_58_28-Download Visual Studio Tools - Install Free for Windows, Mac, Linux and 5 more p](https://user-images.githubusercontent.com/12762442/158595198-51590499-d391-4f49-b977-c07a4ee00c10.png)

and I installed the bare minimum build tools and run the dev environment:

![2022-03-16 14_00_19-](https://user-images.githubusercontent.com/12762442/158609357-4f98a1a9-f510-4da3-9441-8d7359c94d51.png)

However, the `cl.exe`, `nmake.exe`, and `ml.exe` executables are not found yet

![2022-03-16 15_14_08-Administrator_ Developer Command Prompt for VS 2022](https://user-images.githubusercontent.com/12762442/158609833-f144edaa-9375-4db8-83fd-2eac22059fc5.png)

I would appreciate it if you could help me know what the problem is and how I can resolve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#feedback)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-03-16 23:34
@Foadsf 

The "bare minimum" doesn't include the tools you need if you don't select a C++ workload in the Visual Studio Installer. Depending on which version you're installing, the workload might be called **Desktop development with C++** or **Visual C++ build tools**. Either way, this workload should install the MSVC build tools and base libraries, which include the compiler, linker, and nmake. Fortunately, this should be easy to fix. Rerun Visual Studio Installer, choose **Modify**, select the C++ workload, then choose **Modify**. Once it completes, your Developer Command Prompt should give you access to the tools you're looking for. Since these workloads are specifically mentioned in [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170), there's not really a doc issue to address. I'm closing this as a support issue, not a doc issue. Best of luck with your coding.

**Closed by corob-msft** 2022-03-16 23:34 UTC

**Comment by Foadsf** [comment] 2022-03-17 12:07
@corob-msft thanks for the response. However, if I install that then it is already ~7GB!!! why should the command line tools be so big? There is a need for minimal installation just for the standard library header and the compilers. not everyone needs the IDE.

**Comment by AugP** [comment] 2022-03-17 18:13
> @corob-msft thanks for the response. However, if I install that then it is already ~7GB!!! why should the command line tools be so big? There is a need for minimal installation just for the standard library header and the compilers. not everyone needs the IDE.

I agree, this is much bigger than I am happy with and is something we are working on fixing. The problem is we are limited by the UI (my team doesn't have control over it). If we break down the components more granularly, we have to add many new checkboxes which can make it more difficult for users to figure out what they need to check. With vcpkg artifacts, we plan to have a separate way to customize your toolset acquisition experience which will hopefully make it easier to select what you want and be able to get much smaller packages. The bad news is we don't have an ETA yet, but we have engineers working on that feature right now.
