### ISSUE TITLE
Running debug exe

### ISSUE THREAD

**Issue by heuanhomos** [MicrosoftDocs/cpp-docs#2345] opened 2020-08-04 14:07 UTC
Using an exe built with vs2008 - i needed to copy the debug dlls and manifests from the non redist folder (i guess that matches method 2), but got a sxs error.

I ran sxstrace - the version number in the manifest didn't match what the exe wanted. Putting in the older version of the dlls had an incorrect entry point. I had to edit the manifest file to change the version (also removed the sha details) whilst using the new dlls. No idea where these version numbers reside in the vcproj!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3ac071-f6e9-da5a-6fa5-577da31bd308
* Version Independent ID: 92854ad2-954f-e12f-7f7f-f9cec8924548
* Content: [Preparing a Test Machine To Run a Debug Executable](https://docs.microsoft.com/en-us/cpp/windows/preparing-a-test-machine-to-run-a-debug-executable?view=vs-2019)
* Content Source: [docs/windows/preparing-a-test-machine-to-run-a-debug-executable.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/preparing-a-test-machine-to-run-a-debug-executable.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2020-08-05 03:12
Closing as duplicate of MicrosoftDocs/cpp-docs/issues/2346

**Closed by corob-msft** 2020-08-05 03:12 UTC
