### ISSUE TITLE
COM Singleton

### ISSUE THREAD

**Issue by LazyGepid** [MicrosoftDocs/cpp-docs#428] opened 2018-09-13 15:42 UTC
How can I configure a DLL to be able to consume a COM singleton that is an .exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d251d9-04a9-df94-4926-6e76f498fa49
* Version Independent ID: 40e708c0-fc65-ecb4-8c36-9983a2885c77
* Content: [How to: Build Isolated Applications to Consume COM Components](https://docs.microsoft.com/en-us/cpp/build/how-to-build-isolated-applications-to-consume-com-components?view=vs-2017)
* Content Source: [docs/build/how-to-build-isolated-applications-to-consume-com-components.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-build-isolated-applications-to-consume-com-components.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment] 2018-09-25 18:34
@LazyGepid What happens when you try Step #3?: Select the Isolated COM property page, and then set the Component File Name property to the name of the COM component that you want the isolated application to consume.

**Comment by LazyGepid** [comment] 2018-09-25 18:43
At this point I've given up, but I'm pretty sure I got the standard "class not registered" error when trying to create an instance of the COM singleton from within the DLL.

**Comment by mikeblome** [comment] 2018-09-25 18:55
Hmmm. I would guess that the issue is with the .exe registration itself.  If you decide to come back to it, this link might be relevant: https://stackoverflow.com/questions/12979501/registry-keys-for-out-of-process-com-server.
I'll go ahead and close this issue unless you think there's a reason to keep it open.

**Comment by LazyGepid** [comment] 2018-09-25 19:45
It works if I use normal COM registration.  I just want to be able to have a DLL make use of a COM .exe that resides in the same directory and not let anything else use that COM .exe.  The complication comes from the fact that this configuration is an ActiveX DLL that needs to have multiple instances be able to use a COM singleton.  I suppose I could make the COM singleton be a standard process and communicate with it some other way (e.g. named pipes), but the COM method call and event dispatch mechanism works well for what is being done.

Also, FYI, I've found cases of other developers trying to make an isolated COM singleton but none have been able to succeed.  That's why I was wondering if isolated COM was meant for use with a singleton .exe.

**Comment by mikeblome** [comment] 2019-03-18 18:00
@LazyGepid if this is still an issue for you, I suggest asking on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Closed by mikeblome** 2019-03-18 18:00 UTC
