### ISSUE TITLE
How do we know when to "remove the /Wv option in your build as soon as practical"?

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/cpp-docs#3967] opened 2022-06-07 17:32 UTC
[Enter feedback here]
1st para states:  We recommend you always compile at the highest regular warning level, /W4, and remove the /Wv option in your build as soon as practical.

How do we know when? I just had to add 19.24 in a VS 2019 16.11.15 to C++, General, Warning Version, to get C5205 to compile. This was introduced 6 versions earlier that 16.11.15 and still not fixed - will it ever be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672bc066-51a0-9778-4c50-98922ebb4b4c
* Version Independent ID: 6263d065-c81a-54f7-a99d-fef41134c872
* Content: [Compiler Warnings by compiler version](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2022-06-07 20:25
@markyoung2u 
I'm sorry a warning is giving you trouble. All the instances of the C5205 warning I know about have been caused by header files that didn't properly mark base class destructors as `virtual`. Here's one example that required updated WinRT headers: [New warnings when building with VS 2019 16.5](https://github.com/microsoft/cppwinrt/issues/560). To resolve the issue, track down the source for the warning (presumably a base class of whatever class is being destroyed when you see C5205). If it's a header you control, then you can fix it yourself. If it's in a header for a library, check and see if an update is available. Libraries you get from vcpkg or nuget are probably easier to update than libraries you obtain other ways.

The docs are telling you to remove **`/Wv`** when the source is fixed so the diagnostics don't appear anymore. Finding and fixing the issue is up to you. Since this isn't a documentation issue on its own, I'm closing it. Best of luck with your code.

**Comment by markyoung2u** [comment] 2022-06-07 22:45
OK. Thanks

**Closed** 2022-06-08 21:32 UTC
Labels: Closed - not a doc issue
