### ISSUE TITLE
error C4296: '<': expression is always false - low priority avoidable bugged in kernel driver

### ISSUE THREAD

**Issue by Jurugi** [MicrosoftDocs/cpp-docs#3530] opened 2021-11-18 16:04 UTC
Dynamically reading memory in a kernel driver leads to: error C4296: '<': expression is always false

`DWORD64 ThisPtr = a valid addr;
DWORD64 Index = *(BYTE*)(dwSignatures[2] + 0x34); // get index
Index = *(DWORD*)(ThisPtr + Index);
if (Index < 0 || Index > 100) return 0;`

for some reason in this format, it refuses to compile but does not know yet Index value (after reading 4 bytes in the prior line)

To resolve I cannot turn the error off or warning/error level down in settings because it's actually an error now

I changed DWORD64 Index -> int Index and it now works even tho that should not make a difference.

WDK with version 10.0.19041.0, Visual Studio 2019 (and up)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3502f0a7-4976-76ba-ee7b-50270b74c7c1
* Version Independent ID: 8f69af7d-1d67-e59c-eadb-d90ead744357
* Content: [Compiler Warning (level 4) C4296](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4296?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4296.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4296.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-11-18 18:57
@Jurugi 
Sorry it's confusing. `DWORD64` is a typedef for `unsigned __int64`, so your expression `if (Index < 0 || Index > 100)` triggers the warning. Unsigned values can't be less than zero, so that first `Index < 0` expression is always `false`. For a quick clue about exactly which expression the compiler is complaining about, add the [`/diagnostics:caret`](https://docs.microsoft.com/cpp/build/reference/diagnostics-compiler-diagnostic-options) option to the compiler. It can help you spot such issues quickly.

Closing the issue, as this behavior is by design, and not a documentation issue.

**Closed by corob-msft** 2021-11-18 18:57 UTC
Labels: Closed - by design

**Comment by Jurugi** [comment] 2021-11-30 01:46
I agree, but it's not confusing. It's becauseof the typedef definition being enforced as an error.

 If you happened to read one and it had a signed value of a negative value, then being <0 will be true anyway, but it technically 'does not know' yet. e.g. with *(int*) or *(DWORD*) it's just going to compile in memory to 'read 4 bytes' no matter the typedef (int or dword), then compare with a value, the signed/unsigned typedef is only a C or C++ object typedef that sort of labels it but makes no difference.

Apologies as searching didn't show much on this, nor reveal that it's the problem.. (unsigned/signed typedef becomes error)

It's not really a bug either and does not need to be fixed as long as it's clear.

So if anyone runs into this issue, the solution is changing unsigned long (long) to int(64) which will hold '4' or '8' address space.
even tho in memory/C it does not discern the difference, and it was working before, they are likely adding this at some point for code clarity.

If it's now 'by design' hopefully this clear up any issues people have in the future if it's searchable.
