### ISSUE TITLE
Error 4244

### ISSUE THREAD

**Issue by bumblebritches57** [MicrosoftDocs/cpp-docs#380] opened 2018-08-07 12:57 UTC
It'd be great if you guys could tell us how to deal with this issue for functions that implicitly return different types, like PeekBits, ReadBits, and ReadUnary from [FoundationIO's BitIO](https://github.com/bumblebritches57/FoundationIO/blob/master/libFoundationIO/src/BitIO.c)

Currently, I'm wrapping the declaration of those functions in

`
#pragma warning(push)
#pragma warning(disable: 4244)
#pragma warning(pop)
`

But it's not actually working for some unknown reason...

and you shouldn't cast the return value of a function in C because it mask's errors, so I'd prefer to not do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 490f48ea-a4c9-572c-047b-057244aaf2f4
* Version Independent ID: 14cdbd3e-5a3d-cafa-6d35-85422feeaf5e
* Content: [Compiler Warning (levels 3 and 4) C4244](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C4244)%26rd%3Dtrue)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2018-08-07 18:42
Hi, @bumblebritches57 -

I'm not sure I understand the problem. If you assign an unsigned 64-bit value to either a signed type or a type that's less than 64-bits, you'll get the C4244 truncation warning. This is good, because you shouldn't do that unless you intend to, and the way you signal your intent to the compiler is with an explicit cast. I also don't understand your concern about casting the result of a function call. There's nothing special about values returned by functions; they are as safe or unsafe to cast as any other value. Casting leads to unexpected behavior only when you don't understand what the cast does. In this regard, C++ is a little better than C about making casts understandable.

From a proper engineering standpoint, use of a cast is preferable to silencing the warning, but if you really want to, one way to do it is shown in this example: 

```
// disable4244.c
// compile using: cl /W4 disable4244.c
#include <stdio.h>

unsigned long long foo() {
    return 0x8070605040302010ULL;
}

int main() {
    int a, b, c, d, e;
    a = foo();             // C4244
#pragma warning ( push )
#pragma warning ( disable : 4244 )
    b = foo();             // no warning
#pragma warning ( pop )
    c = foo();             // C4244 again
    d = (int)foo();        // explicit cast, no warning
    e = (int)(foo() >> 32);// get high-order bits, interpret as int
    printf("%d\n", e);     // 0x80706050 is -2140118960 as an int
    return 0;
}
```

**Comment by bumblebritches57** [comment] 2018-08-07 19:11
Hi @corob-msft 

I'm not entirely sure what you're confused about?

ReadBits for example returns X bits that have been read, usually X is considerably lower than 64.
One of my projects is reading a WAV file, let's say we're reading the file magic `BM` aka 0x424D

I'd store that file magic in a uint16_t variable, because that's all the data it contains, anything else is a waste.

Because of that, I'm getting that warning.

I tried suppressing that warning with the following:


#pragma warning(push)
#pragma warning(disable: 4244)
    uint64_t ReadBits(ByteBitOrders ByteOrder, ByteBitOrders BitOrder, BitBuffer *BitB, const uint8_t Bits2Read);
#pragma warning(pop)


Providing 8 different functions (signed/unsigned, 8, 16, 32, 64) bit versions of the ReadBits functions simply is not possible.

Firstly, because it's a ridiculous amount of overhead, and second, because you guys don't support _Generics, not to mention that would be abusing the _Generic mechanism in the first place.

So, the problem is, why is your compiler ignoring that pragma in the first place?

My warning level is set to 3.

For the rest of the parameters in my VCProject file, feel free to look in `FoundationIO/Projects/libFoundationIO.vcxproj`

FoundationIO is a library, I couldn't possibly put that pragma around each and every call to ReadBits, it's external...

**Comment by bumblebritches57** [comment] 2018-08-07 19:35
Why is it a problem that this error isn't surpressed in this context?

because only today did I realize it was a real warning that ws pointing out actual bugs in my code, before that I was ignoring it.

That's an abysmal security failure...

**Comment by corob-msft** [comment] 2018-08-07 19:35
I think I see the problem now. You're trying to turn the warning off on a declaration; that can't work. The compiler generates warning C4244 wherever a truncating assignment is made, and it doesn't matter what the source of the larger value is. 

If this is your library, then it should be easy to make some trivial functions that return smaller types if that's what you want callers to use. For example,

```
    uint8_t ReadBitsU8(ByteBitOrders ByteOrder, ByteBitOrders BitOrder, BitBuffer *BitB) {
        return (uint8_t)ReadBits(ByteOrder, BitOrder, BitB, 8);
    }
```

Library writers provide this kind of convenience all the time. This would be even easier in C++, where you can use template functions to create overloads with the same function name. Otherwise, you need to tell your callers to cast the result of your existing functions to the types they need.

**Comment by corob-msft** [comment] 2018-08-09 17:39
Closing this now as not a specific documentation issue.

**Closed by corob-msft** 2018-08-09 17:39 UTC
