### ISSUE TITLE
No c++ exceptions from CSimpleArray and  CSimpleMap

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2575] opened 2020-11-05 13:40 UTC
`ATL::AtlThrowImpl()` can be compiled to throw c++ exceptions or raise [SE](https://en.wikipedia.org/wiki/Microsoft-specific_exception_handling_mechanisms), regarding the existence of `_ATL_NO_EXCEPTIONS` at compile time.

The problem: `ATL::CSimpleArray<T>` **does not use** `AtlThrow`. Thus even if the host is compiled to use C++ exceptions, `CSimpleArray` instance will raise the Structured Exception on e.g. range error in its `operator []`.

The same issue is with `ATL::CSimpleMap<K,V>` 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8134a2a-bd1c-2fae-fdb2-f3268bd20c44
* Version Independent ID: 6b316148-edfc-50c5-20c6-d2a91721b03a
* Content: [CSimpleArray Class](https://docs.microsoft.com/en-us/cpp/atl/reference/csimplearray-class?view=msvc-160)
* Content Source: [docs/atl/reference/csimplearray-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/csimplearray-class.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment] 2020-11-05 23:48
@DBJDBJ 
Thanks for the report. This doesn't sound like a documentation issue, in and of itself. If you think this represents a defect in the library, the place to raise the issue is on [Developer Community](https://aka.ms/feedback/report?space=62), which the development team monitors for product issues. If the development team determines that the documentation also needs an update, they'll let us know. Until then, I'll close it. If you report the issue on Developer Community, would you mind adding a link to the issue in a comment here? That will help us link the issues if and when it gets back to us. Thanks!

**Closed by corob-msft** 2020-11-05 23:48 UTC
Labels: product-feedback

**Comment by DBJDBJ** [comment] 2020-11-06 03:29
https://developercommunity.visualstudio.com/content/problem/1246581/atl-csimplearray-and-csimplemap.html
