### ISSUE TITLE
Constructors - Get_Contents() method is misnamed

### ISSUE THREAD

**Issue by ilyash-b** [MicrosoftDocs/cpp-docs#1929] opened 2020-02-23 14:34 UTC
https://github.com/MicrosoftDocs/cpp-docs/blob/dfb428f10bee0c50f27036c50391ae743e9b0b31/docs/cpp/constructors-cpp.md#L235-L241

* The method actually prints and does not return anything
* On the very basic level `Get_...` named method returns type `void` - nope

**Comment by corob-msft** [comment] 2020-02-24 12:39
@ilyash-b 

It sounds as if you're suggesting that the sample function name doesn't follow a particular naming convention for accessors. You're welcome to make a PR to change it if you care to, but the convention is hardly universal, and the code is not defective otherwise. I'm closing this as something I wouldn't bother to fix, as the name is suggestive of what the function does to people who aren't adopters of that particular convention.

**Comment by ilyash-b** [comment] 2020-02-24 13:19
> It sounds as if you're suggesting that the sample function name doesn't follow a particular naming convention for accessors.

No. I'm saying there is a mismatch between the name of the method and what it does.

> naming convention for accessors

It's not an accessor. (While the name suggests it is).

> code is not defective otherwise

Mismatch between the name of the method and what it does would generally not pass code review.

> name is suggestive of what the function does

No, it is not

**Comment by ilyash-b** [comment] 2020-02-28 09:33
@corob-msft , are you taking second look at this after my comment?

**Comment by corob-msft** [comment] 2020-02-28 12:39
@ilyash-b 
I have indeed looked again, and I still don't see your PR.

As an aside, your argument consists solely of assertions. It makes no citations. It doesn't even make an appeal to authority. That's not to say that there's no better argument to be made. The problem is that you haven't made *any* argument yet. The hilarious part, to me anyway, is that I agree with you about this particular convention. Member functions named with some variant of "get" or "set" *ought* to be accessors and mutators. But here's the thing - they don't have to be! Out there in the real world of code, often they aren't. Lots of code predates the whole object-oriented "property" business, of hiding private data fields behind public methods. "Get" can have just as expansive a meaning as it does in English. Maybe it returns something. Maybe it prints something. Maybe it pulls a token off of a stream and sticks it in a buffer. Those are all plausible meanings for "get." I have seen code using the name "get" do every one of those things. Making "get" exclusive to accessors is just a convention. Not a standard. Here, have a quote from Bjarne Stroustrup's *The C++ Programming Language, Fourth Edition*, section 8.3.2, page 216:

>```
>    //...
>    int number() const;
>    string text() const;
>
>    void set_number(int n);
>    void set_text(const string&);
>    //...
>};
>```
>I'm not a fan of get/set functions, but in this case we really need to perform a nontrivial user-specified action on each access. I chose to name the "get" function after the value, and use the **set_** prefix for the "set" function. That happens to be my favorite among the many naming conventions.

Also, have you considered making a PR.

**Comment by ilyash-b** [comment] 2020-02-28 16:34
First, I probably misunderstood your first comment and therefore I was answering something different than what you meant. That is because it was really hard for me to imagine a method called `Get`-something which doesn not return anything.

>  I have indeed looked again, and I still don't see your PR.

This sounds like an attempt to put me in an uncomfortable position.

I am not paid for this. Therefore, I decide on the type and amount of my contributions. I spotted something that I consider to be an issue and I would like to report it and discuss it. That doesn't mean I'm willing at this point in time to contribute in some additional way.

> It makes no citations. It doesn't even make an appeal to authority. 

Let's that, I guess?

* https://isocpp.org sounds like an authority. https://isocpp.org/wiki/faq/coding-standards#coding-std-wars lists 2 online resources and one book. Not buying the book, so let's look at the two online resources:
	* http://stroustrup.com/JSF-AV-rules.pdf
	```
	int32 get_limit (void)  // Sample accessor to be inlined 
	```

	```
	LM_string     get_name () const;
	```
	* http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-get
	( Editors: Bjarne Stroustrup, Herb Sutter )
	```
	int get_x() const { return x; }
	int get_y() const { return y; }
	```
* Several people at lobste.rs [think](https://lobste.rs/s/vkxtdu/get_method_prints) it should be `print`.
* Couple of reactions from another chat:
	* > You are not getting anything from the function, so just go ahead and name it Print_Contents or something similar which better reflects what the function does
	* > I agree \
Always think about if someone else has to read the code or use the code base

> argument

Not sure whether you consider these as arguments but I'll try:

* If you ask a group of developers *today*, how one should call a function that prints contents: `Print_Contents` or `Get_Contents`, *I think* most of them will say the former and that it's much less surprising.
* I can't remember single exposure to any meaning of "get" in context of programming where it meant *not* returning a value.

> Member functions named with some variant of "get" or "set" ought to be accessors and mutators. But here's the thing - they don't have to be! Out there in the real world of code, often they aren't.

I would really like to see that. Can you link to some open-source project(s) where a method that starts with "get" and doesn't return anything?

90% of the code out there is of subpar quality. Chances are that the code where `get` does not return a value is part of these 90%. I don't think that documentation should be aligned with that. People are learning from documentation so it makes sense to set the bar higher?

> "Get" can have just as expansive a meaning as it does in English.

As you claim, the word "get" might mean many different things. "print" is much more specific. So if there is any sense in which "get" is also correct here, "print" would be much more appropriate. The extreme of "get" would be to call the method "Do_Something", which doesn't convey any meaning.

> Maybe it returns something. Maybe it prints something. Maybe it pulls a token off of a stream and sticks it in a buffer. 

returns - fine, prints - misleading, pulls a token off of a stream and sticks it in a buffer - probably ok (hard to say without further details)

> Those are all plausible meanings for "get."

No. Printing is surprising. Maybe not if you have a whole code base that does that but this is documentation, people are looking at this example as a standalone unit.

> I have seen code using the name "get" do every one of those things.

See above regarding code quality.

> Making "get" exclusive to accessors is just a convention. Not a standard. Here, have a quote from Bjarne Stroustrup's 

The quote does not demonstrate your point. It demonstrates a getter which does not start with `get` while your point is that `get` methods are not always getters.

**Comment by corob-msft** [comment] 2020-02-28 20:28
@ilyash-b 

Ilya, I apologize. I have always been of the same opinion about the name as you. I was overtaken by [the imp of the perverse](https://en.wikipedia.org/wiki/The_Imp_of_the_Perverse). And, I knew when I hit the comment button that I'd almost certainly provoke [a response like yours](https://xkcd.com/386/), rather than the kind I'd like to encourage. I feel bad about that. Allow me to start over:

You're right, that function could have a better name. Given our task list, it's unlikely we'll get to this issue anytime soon. Fortunately, it's almost trivially easy to submit a fix for something like this. It's a two-word change in a single article. If you have a GitHub account already, you're about 80% of the way there. It takes less than two minutes. [There's even a video how-to](https://youtu.be/V3h3X08A0DY)\*. So, I'm opening it up to any takers. Get some open source cred and add a little green dot to your GitHub profile. The readers that follow will be better off. Thanks!

\* In the video it literally takes five minutes to explain what it takes one minute to do. (Yes, that's me, in my all my fat, frumpy, flat-affect, awkward glory.)

**Closed** 2020-04-21 07:06 UTC
Labels: doc-enhancement, doc-idea, good-first-PR-issue, help wanted
