### ISSUE TITLE
Error compiling Helloworld project

### ISSUE THREAD

**Issue by simon-beard** [MicrosoftDocs/cpp-docs#3781] opened 2022-03-18 03:39 UTC
First time user here.
Followed instructions , copied code without changes and ran build
Failed to compile, and showed with 3 errors
My project name id DT, 
Any suggestions?
![2022-03-18_14h37_24](https://user-images.githubusercontent.com/10491820/158933165-fb61ff0a-956f-44d2-922f-34c9b5eac6c6.png)
2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-170)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob*
![2022-03-18_14h37_24](https://user-images.githubusercontent.com/10491820/158933246-e74e02b5-2f0c-481c-adb6-53dba7098f9a.png)
*

**Comment by corob-msft** [comment] 2022-03-23 00:52
@simon-beard 

I'm sorry the example is giving you trouble. I'm unable to reproduce this result when I follow the walkthrough. There's no apparent issue with the documentation, so I'm closing this as a support issue. From the error messages, it looks like you have two source files in your project that both define a `WndProc` function. There should only be one *`.cpp`* source file in your project. For additional support, you can try [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck with your project.

**Closed by corob-msft** 2022-03-23 00:52 UTC
Labels: support-request, Closed - not a doc issue
