### ISSUE TITLE
This is inadequate as this error occurs in much more complex situations where it is impossible to understand why it occurs

### ISSUE THREAD

**Issue by ChrisJ60** [MicrosoftDocs/cpp-docs#998] opened 2019-05-10 11:59 UTC
Here is an example:

I have a function defined as follows:

static int sbThreadJoin(sbThread t, void** statusPP, int* errorP)
{
...
}

and later it is called thus:

rc = sbThreadJoin(threadInfo[t].tid, (void **)NULL, (int *)NULL);

which gives the cryptic error:

error C2120: 'void' illegal with all types

Much googling has not yielded any useful explanation of why the compiler is complaining about this or how to resolve the issue.

This code (of course) compiles fine on Linux and macOS...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a10f869-bab6-436e-0abb-04269859ba7d
* Version Independent ID: 2d9d1f8e-6af6-42d8-4d2e-1ad844c58c6e
* Content: [Compiler Error C2120](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2120?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2120.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2120.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2019-05-10 19:06
@ChrisJ60 
Sorry you're running into trouble. If other compilers are happy with code that MSVC doesn't like, it's often because of differences in headers, or different diagnostic options. The first thing I'd do is turn on the `/diagnostics:caret` option to find out what symbol the compiler is complaining about. (In the IDE, it's found in your project's **Property Pages** dialog, under **Configuration Properties > C/C++ > General**, in the **Diagnostics Format** property.) I'd then use IntelliSense in the editor to see what the compiler thinks that symbol is (just hover the pointer over it). It might be something unexpected. If that's true, then there's your explanation. I'd note that use of C-style casts can be a problem, especially with things that might look like the Most Vexing Parse to the compiler. I'm not saying that's the issue here, it's just common.

I built some minimal repro code using the compiler defaults, and couldn't reproduce your issue:

```
// issue998.cpp
// test of C2120

#include <vector>

struct sbThread {};
struct threadinfo_t
{
	sbThread tid;
};

static int sbThreadJoin(sbThread t, void** statusPP, int* errorP)
{
	return 42;
}

int main()
{
	std::vector<threadinfo_t> threadInfo;
	sbThread sb;
	threadinfo_t ti{ sb };
	threadInfo.push_back(ti);
	size_t t = 0;
	int rc = 0;

	rc = sbThreadJoin(threadInfo[t].tid, (void**)NULL, (int*)NULL);
}
```

```
C:\Users\corob\Source\Repos\Project8\Project8>cl /EHsc /W3 /diagnostics:caret issue998.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27030.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

issue998.cpp
Microsoft (R) Incremental Linker Version 14.16.27030.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:issue998.exe
issue998.obj
```

If you think the compiler is misbehaving, the thing to do is report it via [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). There are comprehensive instructions in [How to report a problem with the Visual C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019). 

I'm closing this issue, but don't consider this the last word. If it turns out you've found a new kind of case that triggers C2120, something that doesn't look like you're applying `void` to another type, get back to us and reopen this issue, and we'll add something about it to the documentation. There's no way for us to enumerate every possible way to generate each error, so we try to cover the base cases, and rely on developer detective work to see how their situation applies.

**Closed by corob-msft** 2019-05-10 19:06 UTC
Labels: docs-experience, needs-more-info, support-request
