### ISSUE TITLE
gets_s does more than the documentation describes

### ISSUE THREAD

**Issue by SteveWTF** [MicrosoftDocs/cpp-docs#1667] opened 2019-10-27 19:15 UTC
Switching from gets to gets_s caused my program to crash. I did not know the length of the buffer so I entered a really big number. The gets_s does what the documentation describes but it also continues to put stuff into memory after the terminating null character. It pads 0xFE to every byte after the terminating null character up to the length of the buffer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6a3b86-cdb0-2d96-d61b-38dd9f4964e0
* Version Independent ID: 02427c3f-c55c-8fac-4784-693679c0de71
* Content: [gets, _getws](https://docs.microsoft.com/en-us/cpp/c-runtime-library/gets-getws?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/gets-getws.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/gets-getws.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2019-10-28 00:26
Closing as duplicate of #1668.

**Closed by corob-msft** 2019-10-28 00:26 UTC
Labels: duplicate
