### ISSUE TITLE
Where is NULL defined?

### ISSUE THREAD

**Issue by Pekka-Kalevi** [MicrosoftDocs/cpp-docs#3232] opened 2021-07-01 10:58 UTC
NULL is actually defined in the following header file:

 "C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\CORECRT.H"

File: corecrt.h Line: 244, 248

#ifndef NULL
    #ifdef __cplusplus
        #define NULL 0
    #else
        #define NULL ((void *)0)
    #endif
#endif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2325582b-6542-6543-b8f4-e00b089d8f85
* Version Independent ID: 98054d7c-13d0-926c-8307-2fb0b80ac5b6
* Content: [NULL (CRT)](https://docs.microsoft.com/en-us/cpp/c-runtime-library/null-crt?view=msvc-160)
* Content Source: [docs/c-runtime-library/null-crt.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/null-crt.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment] 2021-07-01 22:36
Closing as a duplicate of the more elaborated #3233 issue.

**Closed by corob-msft** 2021-07-01 22:36 UTC
Labels: duplicate
