### ISSUE TITLE
additional include paths on a different drive letter

### ISSUE THREAD

**Issue by MrDavid949** [MicrosoftDocs/cpp-docs#3086] opened 2021-04-14 00:56 UTC
Hi,

  How do you specify additional include paths if the path is on a different driver letter?  Using /I"D:\My Path\include\" does not work.

thank you
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec7ea59-1270-7e09-8240-651d34d7e758
* Version Independent ID: e004b9b0-4031-8bd9-b2bf-247656829ebe
* Content: [/I (Additional include directories)](https://docs.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-160)
* Content Source: [docs/build/reference/i-additional-include-directories.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/i-additional-include-directories.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment] 2021-04-14 11:50
@MrDavid949 
Sorry you're having trouble. I tried it with success. I had my source file on the C: drive in *`C:\projects\include\sample.cpp`* and an include file at *`D:\include\include.h`*. I used a command line of **`cl /EHsc /I"D:\include" sample.cpp`**. In sample.cpp, I tried referring to the include file as `#include <include.h>` and as `#include "include.h"` and both worked fine. I recommend experimenting, and if you're still having trouble, you could try the [C++ Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) forum. I'm closing this, as it seems like a support issue rather than a documentation issue.

**Closed by corob-msft** 2021-04-14 11:50 UTC
Labels: support-request

**Comment by MrDavid949** [comment] 2021-04-14 21:15
Hi Colin, this is not fully working if there is a space in the path.  Specifically, I was using x64 cl.exe that is on the Server 2022 20329 EWDK and my command line argument contains:  /I"D:\Program Files\Windows Kits\10\10.0.20329.0\shared\"

This causes cl.exe to output:
cl : Command line error D8038 : invalid argument 'D:\Program Files\Windows Kits\10\10.0.20329.0\shared"

Maybe it must be done another way if the path contains spaces?  The documentation does not say anything about such a case.

**Comment by corob-msft** [comment] 2021-04-14 22:24
@MrDavid949 
Curious. My experiments with paths that have spaces also succeed. I'm using the x64 CL as well:

```cmd
C:\Projects\curiosity\include_space>type sample.cpp
// sample.cpp
#include <iostream>
#include "include.h"

int main()
{
    Sample s;
    s.set_value(6);
    if (s.get_value() != 0)
        std::cout << "Sample s has a non-zero value.\n";
    else
        std::cout << "Sample s is zero.\n";
    return 0;
}
C:\Projects\curiosity\include_space>type "D:\include files\that include files\in directories with spaces\include.h"
// include.h
struct Sample {
    int get_value() { return _value; }
    int set_value( int new_value ) { auto old_value = _value; _value = new_value; return old_value; }
private:
    int _value = 0;
};

C:\Projects\curiosity\include_space>cl /EHsc /W4 /permissive- /I"D:\include files\that include files\in directories with spaces" sample.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

sample.cpp
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:sample.exe
sample.obj

C:\Projects\curiosity\include_space>sample
Sample s has a non-zero value.
```

I suspect something else is going on in your command line, but I'm at a loss as to what. You might get more informed answers by asking this question on the [Developer Community](https://aka.ms/vsfeedback/browsecpp) site. I'm not reopening the issue yet, since I'm unable to reproduce it, but if you should find something that does need updating or clarifying in the docs, please circle back and let us know.
